/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.register': {
    methods: ["POST"],
    pattern: '/api/auth/register',
    tokens: [{"old":"/api/auth/register","type":0,"val":"api","end":""},{"old":"/api/auth/register","type":0,"val":"auth","end":""},{"old":"/api/auth/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.register']['types'],
  },
  'auth.login': {
    methods: ["POST"],
    pattern: '/api/auth/login',
    tokens: [{"old":"/api/auth/login","type":0,"val":"api","end":""},{"old":"/api/auth/login","type":0,"val":"auth","end":""},{"old":"/api/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/me',
    tokens: [{"old":"/api/auth/me","type":0,"val":"api","end":""},{"old":"/api/auth/me","type":0,"val":"auth","end":""},{"old":"/api/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['auth.me']['types'],
  },
  'shops.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/shops',
    tokens: [{"old":"/api/shops","type":0,"val":"api","end":""},{"old":"/api/shops","type":0,"val":"shops","end":""}],
    types: placeholder as Registry['shops.index']['types'],
  },
  'shops.store': {
    methods: ["POST"],
    pattern: '/api/shops',
    tokens: [{"old":"/api/shops","type":0,"val":"api","end":""},{"old":"/api/shops","type":0,"val":"shops","end":""}],
    types: placeholder as Registry['shops.store']['types'],
  },
  'shops.find_or_create': {
    methods: ["POST"],
    pattern: '/api/shops/find-or-create',
    tokens: [{"old":"/api/shops/find-or-create","type":0,"val":"api","end":""},{"old":"/api/shops/find-or-create","type":0,"val":"shops","end":""},{"old":"/api/shops/find-or-create","type":0,"val":"find-or-create","end":""}],
    types: placeholder as Registry['shops.find_or_create']['types'],
  },
  'shops.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/shops/:id',
    tokens: [{"old":"/api/shops/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shops.show']['types'],
  },
  'shops.update': {
    methods: ["PUT"],
    pattern: '/api/shops/:id',
    tokens: [{"old":"/api/shops/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shops.update']['types'],
  },
  'shops.destroy': {
    methods: ["DELETE"],
    pattern: '/api/shops/:id',
    tokens: [{"old":"/api/shops/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shops.destroy']['types'],
  },
  'keywords.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/shops/:shopId/keywords',
    tokens: [{"old":"/api/shops/:shopId/keywords","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/keywords","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/keywords","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/keywords","type":0,"val":"keywords","end":""}],
    types: placeholder as Registry['keywords.index']['types'],
  },
  'keywords.store': {
    methods: ["POST"],
    pattern: '/api/shops/:shopId/keywords',
    tokens: [{"old":"/api/shops/:shopId/keywords","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/keywords","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/keywords","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/keywords","type":0,"val":"keywords","end":""}],
    types: placeholder as Registry['keywords.store']['types'],
  },
  'keywords.destroy': {
    methods: ["DELETE"],
    pattern: '/api/shops/:shopId/keywords/:id',
    tokens: [{"old":"/api/shops/:shopId/keywords/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/keywords/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/keywords/:id","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/keywords/:id","type":0,"val":"keywords","end":""},{"old":"/api/shops/:shopId/keywords/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['keywords.destroy']['types'],
  },
  'templates.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/shops/:shopId/templates',
    tokens: [{"old":"/api/shops/:shopId/templates","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/templates","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/templates","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['templates.index']['types'],
  },
  'templates.store': {
    methods: ["POST"],
    pattern: '/api/shops/:shopId/templates',
    tokens: [{"old":"/api/shops/:shopId/templates","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/templates","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/templates","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['templates.store']['types'],
  },
  'templates.destroy': {
    methods: ["DELETE"],
    pattern: '/api/shops/:shopId/templates/:id',
    tokens: [{"old":"/api/shops/:shopId/templates/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/templates/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/templates/:id","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/templates/:id","type":0,"val":"templates","end":""},{"old":"/api/shops/:shopId/templates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['templates.destroy']['types'],
  },
  'products.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/products',
    tokens: [{"old":"/api/products","type":0,"val":"api","end":""},{"old":"/api/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.index']['types'],
  },
  'products.store': {
    methods: ["POST"],
    pattern: '/api/products',
    tokens: [{"old":"/api/products","type":0,"val":"api","end":""},{"old":"/api/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.store']['types'],
  },
  'products.update': {
    methods: ["PUT"],
    pattern: '/api/products/:id',
    tokens: [{"old":"/api/products/:id","type":0,"val":"api","end":""},{"old":"/api/products/:id","type":0,"val":"products","end":""},{"old":"/api/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.update']['types'],
  },
  'products.destroy': {
    methods: ["DELETE"],
    pattern: '/api/products/:id',
    tokens: [{"old":"/api/products/:id","type":0,"val":"api","end":""},{"old":"/api/products/:id","type":0,"val":"products","end":""},{"old":"/api/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.destroy']['types'],
  },
  'categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/categories',
    tokens: [{"old":"/api/categories","type":0,"val":"api","end":""},{"old":"/api/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['categories.index']['types'],
  },
  'categories.store': {
    methods: ["POST"],
    pattern: '/api/categories',
    tokens: [{"old":"/api/categories","type":0,"val":"api","end":""},{"old":"/api/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['categories.store']['types'],
  },
  'categories.update': {
    methods: ["PUT"],
    pattern: '/api/categories/:id',
    tokens: [{"old":"/api/categories/:id","type":0,"val":"api","end":""},{"old":"/api/categories/:id","type":0,"val":"categories","end":""},{"old":"/api/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categories.update']['types'],
  },
  'categories.destroy': {
    methods: ["DELETE"],
    pattern: '/api/categories/:id',
    tokens: [{"old":"/api/categories/:id","type":0,"val":"api","end":""},{"old":"/api/categories/:id","type":0,"val":"categories","end":""},{"old":"/api/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categories.destroy']['types'],
  },
  'brands.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/brands',
    tokens: [{"old":"/api/brands","type":0,"val":"api","end":""},{"old":"/api/brands","type":0,"val":"brands","end":""}],
    types: placeholder as Registry['brands.index']['types'],
  },
  'brands.store': {
    methods: ["POST"],
    pattern: '/api/brands',
    tokens: [{"old":"/api/brands","type":0,"val":"api","end":""},{"old":"/api/brands","type":0,"val":"brands","end":""}],
    types: placeholder as Registry['brands.store']['types'],
  },
  'brands.update': {
    methods: ["PUT"],
    pattern: '/api/brands/:id',
    tokens: [{"old":"/api/brands/:id","type":0,"val":"api","end":""},{"old":"/api/brands/:id","type":0,"val":"brands","end":""},{"old":"/api/brands/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['brands.update']['types'],
  },
  'brands.destroy': {
    methods: ["DELETE"],
    pattern: '/api/brands/:id',
    tokens: [{"old":"/api/brands/:id","type":0,"val":"api","end":""},{"old":"/api/brands/:id","type":0,"val":"brands","end":""},{"old":"/api/brands/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['brands.destroy']['types'],
  },
  'leads.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/leads',
    tokens: [{"old":"/api/leads","type":0,"val":"api","end":""},{"old":"/api/leads","type":0,"val":"leads","end":""}],
    types: placeholder as Registry['leads.index']['types'],
  },
  'leads.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/leads/stats',
    tokens: [{"old":"/api/leads/stats","type":0,"val":"api","end":""},{"old":"/api/leads/stats","type":0,"val":"leads","end":""},{"old":"/api/leads/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['leads.stats']['types'],
  },
  'leads.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/leads/:id',
    tokens: [{"old":"/api/leads/:id","type":0,"val":"api","end":""},{"old":"/api/leads/:id","type":0,"val":"leads","end":""},{"old":"/api/leads/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leads.show']['types'],
  },
  'leads.update': {
    methods: ["PUT"],
    pattern: '/api/leads/:id',
    tokens: [{"old":"/api/leads/:id","type":0,"val":"api","end":""},{"old":"/api/leads/:id","type":0,"val":"leads","end":""},{"old":"/api/leads/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leads.update']['types'],
  },
  'leads.destroy': {
    methods: ["DELETE"],
    pattern: '/api/leads/:id',
    tokens: [{"old":"/api/leads/:id","type":0,"val":"api","end":""},{"old":"/api/leads/:id","type":0,"val":"leads","end":""},{"old":"/api/leads/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leads.destroy']['types'],
  },
  'leads.pipeline_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/leads-pipeline',
    tokens: [{"old":"/api/leads-pipeline","type":0,"val":"api","end":""},{"old":"/api/leads-pipeline","type":0,"val":"leads-pipeline","end":""}],
    types: placeholder as Registry['leads.pipeline_stats']['types'],
  },
  'dashboard.overview': {
    methods: ["GET","HEAD"],
    pattern: '/api/dashboard/overview',
    tokens: [{"old":"/api/dashboard/overview","type":0,"val":"api","end":""},{"old":"/api/dashboard/overview","type":0,"val":"dashboard","end":""},{"old":"/api/dashboard/overview","type":0,"val":"overview","end":""}],
    types: placeholder as Registry['dashboard.overview']['types'],
  },
  'dashboard.recent_leads': {
    methods: ["GET","HEAD"],
    pattern: '/api/dashboard/recent-leads',
    tokens: [{"old":"/api/dashboard/recent-leads","type":0,"val":"api","end":""},{"old":"/api/dashboard/recent-leads","type":0,"val":"dashboard","end":""},{"old":"/api/dashboard/recent-leads","type":0,"val":"recent-leads","end":""}],
    types: placeholder as Registry['dashboard.recent_leads']['types'],
  },
  'dashboard.analytics': {
    methods: ["GET","HEAD"],
    pattern: '/api/dashboard/analytics',
    tokens: [{"old":"/api/dashboard/analytics","type":0,"val":"api","end":""},{"old":"/api/dashboard/analytics","type":0,"val":"dashboard","end":""},{"old":"/api/dashboard/analytics","type":0,"val":"analytics","end":""}],
    types: placeholder as Registry['dashboard.analytics']['types'],
  },
  'dashboard.top_customers': {
    methods: ["GET","HEAD"],
    pattern: '/api/dashboard/top-customers',
    tokens: [{"old":"/api/dashboard/top-customers","type":0,"val":"api","end":""},{"old":"/api/dashboard/top-customers","type":0,"val":"dashboard","end":""},{"old":"/api/dashboard/top-customers","type":0,"val":"top-customers","end":""}],
    types: placeholder as Registry['dashboard.top_customers']['types'],
  },
  'analytics.daily': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/daily',
    tokens: [{"old":"/api/analytics/daily","type":0,"val":"api","end":""},{"old":"/api/analytics/daily","type":0,"val":"analytics","end":""},{"old":"/api/analytics/daily","type":0,"val":"daily","end":""}],
    types: placeholder as Registry['analytics.daily']['types'],
  },
  'analytics.hourly': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/hourly',
    tokens: [{"old":"/api/analytics/hourly","type":0,"val":"api","end":""},{"old":"/api/analytics/hourly","type":0,"val":"analytics","end":""},{"old":"/api/analytics/hourly","type":0,"val":"hourly","end":""}],
    types: placeholder as Registry['analytics.hourly']['types'],
  },
  'analytics.conversion': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/conversion',
    tokens: [{"old":"/api/analytics/conversion","type":0,"val":"api","end":""},{"old":"/api/analytics/conversion","type":0,"val":"analytics","end":""},{"old":"/api/analytics/conversion","type":0,"val":"conversion","end":""}],
    types: placeholder as Registry['analytics.conversion']['types'],
  },
  'analytics.top_keywords': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/top-keywords',
    tokens: [{"old":"/api/analytics/top-keywords","type":0,"val":"api","end":""},{"old":"/api/analytics/top-keywords","type":0,"val":"analytics","end":""},{"old":"/api/analytics/top-keywords","type":0,"val":"top-keywords","end":""}],
    types: placeholder as Registry['analytics.top_keywords']['types'],
  },
  'analytics.summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/summary',
    tokens: [{"old":"/api/analytics/summary","type":0,"val":"api","end":""},{"old":"/api/analytics/summary","type":0,"val":"analytics","end":""},{"old":"/api/analytics/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['analytics.summary']['types'],
  },
  'notifications.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/notifications',
    tokens: [{"old":"/api/notifications","type":0,"val":"api","end":""},{"old":"/api/notifications","type":0,"val":"notifications","end":""}],
    types: placeholder as Registry['notifications.index']['types'],
  },
  'notifications.unread_count': {
    methods: ["GET","HEAD"],
    pattern: '/api/notifications/unread-count',
    tokens: [{"old":"/api/notifications/unread-count","type":0,"val":"api","end":""},{"old":"/api/notifications/unread-count","type":0,"val":"notifications","end":""},{"old":"/api/notifications/unread-count","type":0,"val":"unread-count","end":""}],
    types: placeholder as Registry['notifications.unread_count']['types'],
  },
  'notifications.mark_read': {
    methods: ["PUT"],
    pattern: '/api/notifications/:id/read',
    tokens: [{"old":"/api/notifications/:id/read","type":0,"val":"api","end":""},{"old":"/api/notifications/:id/read","type":0,"val":"notifications","end":""},{"old":"/api/notifications/:id/read","type":1,"val":"id","end":""},{"old":"/api/notifications/:id/read","type":0,"val":"read","end":""}],
    types: placeholder as Registry['notifications.mark_read']['types'],
  },
  'notifications.mark_all_read': {
    methods: ["PUT"],
    pattern: '/api/notifications/read-all',
    tokens: [{"old":"/api/notifications/read-all","type":0,"val":"api","end":""},{"old":"/api/notifications/read-all","type":0,"val":"notifications","end":""},{"old":"/api/notifications/read-all","type":0,"val":"read-all","end":""}],
    types: placeholder as Registry['notifications.mark_all_read']['types'],
  },
  'customers.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/customers',
    tokens: [{"old":"/api/customers","type":0,"val":"api","end":""},{"old":"/api/customers","type":0,"val":"customers","end":""}],
    types: placeholder as Registry['customers.index']['types'],
  },
  'customers.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/customers/:id',
    tokens: [{"old":"/api/customers/:id","type":0,"val":"api","end":""},{"old":"/api/customers/:id","type":0,"val":"customers","end":""},{"old":"/api/customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['customers.show']['types'],
  },
  'customers.update': {
    methods: ["PUT"],
    pattern: '/api/customers/:id',
    tokens: [{"old":"/api/customers/:id","type":0,"val":"api","end":""},{"old":"/api/customers/:id","type":0,"val":"customers","end":""},{"old":"/api/customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['customers.update']['types'],
  },
  'customers.destroy': {
    methods: ["DELETE"],
    pattern: '/api/customers/:id',
    tokens: [{"old":"/api/customers/:id","type":0,"val":"api","end":""},{"old":"/api/customers/:id","type":0,"val":"customers","end":""},{"old":"/api/customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['customers.destroy']['types'],
  },
  'sessions.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/sessions',
    tokens: [{"old":"/api/sessions","type":0,"val":"api","end":""},{"old":"/api/sessions","type":0,"val":"sessions","end":""}],
    types: placeholder as Registry['sessions.index']['types'],
  },
  'sessions.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/sessions/:id',
    tokens: [{"old":"/api/sessions/:id","type":0,"val":"api","end":""},{"old":"/api/sessions/:id","type":0,"val":"sessions","end":""},{"old":"/api/sessions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['sessions.show']['types'],
  },
  'orders.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders',
    tokens: [{"old":"/api/orders","type":0,"val":"api","end":""},{"old":"/api/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['orders.index']['types'],
  },
  'orders.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders/stats',
    tokens: [{"old":"/api/orders/stats","type":0,"val":"api","end":""},{"old":"/api/orders/stats","type":0,"val":"orders","end":""},{"old":"/api/orders/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['orders.stats']['types'],
  },
  'orders.store': {
    methods: ["POST"],
    pattern: '/api/orders',
    tokens: [{"old":"/api/orders","type":0,"val":"api","end":""},{"old":"/api/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['orders.store']['types'],
  },
  'orders.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders/:id',
    tokens: [{"old":"/api/orders/:id","type":0,"val":"api","end":""},{"old":"/api/orders/:id","type":0,"val":"orders","end":""},{"old":"/api/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['orders.show']['types'],
  },
  'orders.update': {
    methods: ["PUT"],
    pattern: '/api/orders/:id',
    tokens: [{"old":"/api/orders/:id","type":0,"val":"api","end":""},{"old":"/api/orders/:id","type":0,"val":"orders","end":""},{"old":"/api/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['orders.update']['types'],
  },
  'orders.destroy': {
    methods: ["DELETE"],
    pattern: '/api/orders/:id',
    tokens: [{"old":"/api/orders/:id","type":0,"val":"api","end":""},{"old":"/api/orders/:id","type":0,"val":"orders","end":""},{"old":"/api/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['orders.destroy']['types'],
  },
  'orders.get_details': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders/:id/details',
    tokens: [{"old":"/api/orders/:id/details","type":0,"val":"api","end":""},{"old":"/api/orders/:id/details","type":0,"val":"orders","end":""},{"old":"/api/orders/:id/details","type":1,"val":"id","end":""},{"old":"/api/orders/:id/details","type":0,"val":"details","end":""}],
    types: placeholder as Registry['orders.get_details']['types'],
  },
  'orders.get_totals': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders/:id/totals',
    tokens: [{"old":"/api/orders/:id/totals","type":0,"val":"api","end":""},{"old":"/api/orders/:id/totals","type":0,"val":"orders","end":""},{"old":"/api/orders/:id/totals","type":1,"val":"id","end":""},{"old":"/api/orders/:id/totals","type":0,"val":"totals","end":""}],
    types: placeholder as Registry['orders.get_totals']['types'],
  },
  'orders.get_history': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders/:id/history',
    tokens: [{"old":"/api/orders/:id/history","type":0,"val":"api","end":""},{"old":"/api/orders/:id/history","type":0,"val":"orders","end":""},{"old":"/api/orders/:id/history","type":1,"val":"id","end":""},{"old":"/api/orders/:id/history","type":0,"val":"history","end":""}],
    types: placeholder as Registry['orders.get_history']['types'],
  },
  'orders.update_status': {
    methods: ["PUT"],
    pattern: '/api/orders/:id/status',
    tokens: [{"old":"/api/orders/:id/status","type":0,"val":"api","end":""},{"old":"/api/orders/:id/status","type":0,"val":"orders","end":""},{"old":"/api/orders/:id/status","type":1,"val":"id","end":""},{"old":"/api/orders/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['orders.update_status']['types'],
  },
  'orders.get_order_statuses': {
    methods: ["GET","HEAD"],
    pattern: '/api/order-statuses',
    tokens: [{"old":"/api/order-statuses","type":0,"val":"api","end":""},{"old":"/api/order-statuses","type":0,"val":"order-statuses","end":""}],
    types: placeholder as Registry['orders.get_order_statuses']['types'],
  },
  'orders.get_payment_statuses': {
    methods: ["GET","HEAD"],
    pattern: '/api/payment-statuses',
    tokens: [{"old":"/api/payment-statuses","type":0,"val":"api","end":""},{"old":"/api/payment-statuses","type":0,"val":"payment-statuses","end":""}],
    types: placeholder as Registry['orders.get_payment_statuses']['types'],
  },
  'carts.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/cart',
    tokens: [{"old":"/api/cart","type":0,"val":"api","end":""},{"old":"/api/cart","type":0,"val":"cart","end":""}],
    types: placeholder as Registry['carts.show']['types'],
  },
  'carts.add_item': {
    methods: ["POST"],
    pattern: '/api/cart/items',
    tokens: [{"old":"/api/cart/items","type":0,"val":"api","end":""},{"old":"/api/cart/items","type":0,"val":"cart","end":""},{"old":"/api/cart/items","type":0,"val":"items","end":""}],
    types: placeholder as Registry['carts.add_item']['types'],
  },
  'carts.update_item': {
    methods: ["PUT"],
    pattern: '/api/cart/items/:productId',
    tokens: [{"old":"/api/cart/items/:productId","type":0,"val":"api","end":""},{"old":"/api/cart/items/:productId","type":0,"val":"cart","end":""},{"old":"/api/cart/items/:productId","type":0,"val":"items","end":""},{"old":"/api/cart/items/:productId","type":1,"val":"productId","end":""}],
    types: placeholder as Registry['carts.update_item']['types'],
  },
  'carts.remove_item': {
    methods: ["DELETE"],
    pattern: '/api/cart/items/:productId',
    tokens: [{"old":"/api/cart/items/:productId","type":0,"val":"api","end":""},{"old":"/api/cart/items/:productId","type":0,"val":"cart","end":""},{"old":"/api/cart/items/:productId","type":0,"val":"items","end":""},{"old":"/api/cart/items/:productId","type":1,"val":"productId","end":""}],
    types: placeholder as Registry['carts.remove_item']['types'],
  },
  'carts.checkout': {
    methods: ["POST"],
    pattern: '/api/cart/checkout',
    tokens: [{"old":"/api/cart/checkout","type":0,"val":"api","end":""},{"old":"/api/cart/checkout","type":0,"val":"cart","end":""},{"old":"/api/cart/checkout","type":0,"val":"checkout","end":""}],
    types: placeholder as Registry['carts.checkout']['types'],
  },
  'schedules.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/schedules',
    tokens: [{"old":"/api/schedules","type":0,"val":"api","end":""},{"old":"/api/schedules","type":0,"val":"schedules","end":""}],
    types: placeholder as Registry['schedules.index']['types'],
  },
  'schedules.store': {
    methods: ["POST"],
    pattern: '/api/schedules',
    tokens: [{"old":"/api/schedules","type":0,"val":"api","end":""},{"old":"/api/schedules","type":0,"val":"schedules","end":""}],
    types: placeholder as Registry['schedules.store']['types'],
  },
  'schedules.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/schedules/:id',
    tokens: [{"old":"/api/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['schedules.show']['types'],
  },
  'schedules.update': {
    methods: ["PUT"],
    pattern: '/api/schedules/:id',
    tokens: [{"old":"/api/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['schedules.update']['types'],
  },
  'schedules.destroy': {
    methods: ["DELETE"],
    pattern: '/api/schedules/:id',
    tokens: [{"old":"/api/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['schedules.destroy']['types'],
  },
  'shop_customers.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop-customers',
    tokens: [{"old":"/api/shop-customers","type":0,"val":"api","end":""},{"old":"/api/shop-customers","type":0,"val":"shop-customers","end":""}],
    types: placeholder as Registry['shop_customers.index']['types'],
  },
  'shop_customers.store': {
    methods: ["POST"],
    pattern: '/api/shop-customers',
    tokens: [{"old":"/api/shop-customers","type":0,"val":"api","end":""},{"old":"/api/shop-customers","type":0,"val":"shop-customers","end":""}],
    types: placeholder as Registry['shop_customers.store']['types'],
  },
  'shop_customers.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop-customers/:id',
    tokens: [{"old":"/api/shop-customers/:id","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:id","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shop_customers.show']['types'],
  },
  'shop_customers.update': {
    methods: ["PUT"],
    pattern: '/api/shop-customers/:id',
    tokens: [{"old":"/api/shop-customers/:id","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:id","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shop_customers.update']['types'],
  },
  'shop_customers.destroy': {
    methods: ["DELETE"],
    pattern: '/api/shop-customers/:id',
    tokens: [{"old":"/api/shop-customers/:id","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:id","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shop_customers.destroy']['types'],
  },
  'shop_customers.list_addresses': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop-customers/:customerId/addresses',
    tokens: [{"old":"/api/shop-customers/:customerId/addresses","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:customerId/addresses","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:customerId/addresses","type":1,"val":"customerId","end":""},{"old":"/api/shop-customers/:customerId/addresses","type":0,"val":"addresses","end":""}],
    types: placeholder as Registry['shop_customers.list_addresses']['types'],
  },
  'shop_customers.add_address': {
    methods: ["POST"],
    pattern: '/api/shop-customers/:customerId/addresses',
    tokens: [{"old":"/api/shop-customers/:customerId/addresses","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:customerId/addresses","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:customerId/addresses","type":1,"val":"customerId","end":""},{"old":"/api/shop-customers/:customerId/addresses","type":0,"val":"addresses","end":""}],
    types: placeholder as Registry['shop_customers.add_address']['types'],
  },
  'shop_customers.update_address': {
    methods: ["PUT"],
    pattern: '/api/shop-customers/:customerId/addresses/:id',
    tokens: [{"old":"/api/shop-customers/:customerId/addresses/:id","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":1,"val":"customerId","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":0,"val":"addresses","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shop_customers.update_address']['types'],
  },
  'shop_customers.delete_address': {
    methods: ["DELETE"],
    pattern: '/api/shop-customers/:customerId/addresses/:id',
    tokens: [{"old":"/api/shop-customers/:customerId/addresses/:id","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":1,"val":"customerId","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":0,"val":"addresses","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shop_customers.delete_address']['types'],
  },
  'promotions.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/promotions',
    tokens: [{"old":"/api/promotions","type":0,"val":"api","end":""},{"old":"/api/promotions","type":0,"val":"promotions","end":""}],
    types: placeholder as Registry['promotions.index']['types'],
  },
  'promotions.store': {
    methods: ["POST"],
    pattern: '/api/promotions',
    tokens: [{"old":"/api/promotions","type":0,"val":"api","end":""},{"old":"/api/promotions","type":0,"val":"promotions","end":""}],
    types: placeholder as Registry['promotions.store']['types'],
  },
  'promotions.destroy_promotion': {
    methods: ["DELETE"],
    pattern: '/api/promotions/:productId',
    tokens: [{"old":"/api/promotions/:productId","type":0,"val":"api","end":""},{"old":"/api/promotions/:productId","type":0,"val":"promotions","end":""},{"old":"/api/promotions/:productId","type":1,"val":"productId","end":""}],
    types: placeholder as Registry['promotions.destroy_promotion']['types'],
  },
  'promotions.list_coupons': {
    methods: ["GET","HEAD"],
    pattern: '/api/coupons',
    tokens: [{"old":"/api/coupons","type":0,"val":"api","end":""},{"old":"/api/coupons","type":0,"val":"coupons","end":""}],
    types: placeholder as Registry['promotions.list_coupons']['types'],
  },
  'promotions.store_coupon': {
    methods: ["POST"],
    pattern: '/api/coupons',
    tokens: [{"old":"/api/coupons","type":0,"val":"api","end":""},{"old":"/api/coupons","type":0,"val":"coupons","end":""}],
    types: placeholder as Registry['promotions.store_coupon']['types'],
  },
  'promotions.update_coupon': {
    methods: ["PUT"],
    pattern: '/api/coupons/:id',
    tokens: [{"old":"/api/coupons/:id","type":0,"val":"api","end":""},{"old":"/api/coupons/:id","type":0,"val":"coupons","end":""},{"old":"/api/coupons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['promotions.update_coupon']['types'],
  },
  'promotions.destroy_coupon': {
    methods: ["DELETE"],
    pattern: '/api/coupons/:id',
    tokens: [{"old":"/api/coupons/:id","type":0,"val":"api","end":""},{"old":"/api/coupons/:id","type":0,"val":"coupons","end":""},{"old":"/api/coupons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['promotions.destroy_coupon']['types'],
  },
  'promotions.validate_coupon': {
    methods: ["POST"],
    pattern: '/api/coupons/validate',
    tokens: [{"old":"/api/coupons/validate","type":0,"val":"api","end":""},{"old":"/api/coupons/validate","type":0,"val":"coupons","end":""},{"old":"/api/coupons/validate","type":0,"val":"validate","end":""}],
    types: placeholder as Registry['promotions.validate_coupon']['types'],
  },
  'cms_pages.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/cms-pages',
    tokens: [{"old":"/api/cms-pages","type":0,"val":"api","end":""},{"old":"/api/cms-pages","type":0,"val":"cms-pages","end":""}],
    types: placeholder as Registry['cms_pages.index']['types'],
  },
  'cms_pages.store': {
    methods: ["POST"],
    pattern: '/api/cms-pages',
    tokens: [{"old":"/api/cms-pages","type":0,"val":"api","end":""},{"old":"/api/cms-pages","type":0,"val":"cms-pages","end":""}],
    types: placeholder as Registry['cms_pages.store']['types'],
  },
  'cms_pages.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/cms-pages/:id',
    tokens: [{"old":"/api/cms-pages/:id","type":0,"val":"api","end":""},{"old":"/api/cms-pages/:id","type":0,"val":"cms-pages","end":""},{"old":"/api/cms-pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cms_pages.show']['types'],
  },
  'cms_pages.update': {
    methods: ["PUT"],
    pattern: '/api/cms-pages/:id',
    tokens: [{"old":"/api/cms-pages/:id","type":0,"val":"api","end":""},{"old":"/api/cms-pages/:id","type":0,"val":"cms-pages","end":""},{"old":"/api/cms-pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cms_pages.update']['types'],
  },
  'cms_pages.destroy': {
    methods: ["DELETE"],
    pattern: '/api/cms-pages/:id',
    tokens: [{"old":"/api/cms-pages/:id","type":0,"val":"api","end":""},{"old":"/api/cms-pages/:id","type":0,"val":"cms-pages","end":""},{"old":"/api/cms-pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cms_pages.destroy']['types'],
  },
  'banners_new.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/banners',
    tokens: [{"old":"/api/banners","type":0,"val":"api","end":""},{"old":"/api/banners","type":0,"val":"banners","end":""}],
    types: placeholder as Registry['banners_new.index']['types'],
  },
  'banners_new.store': {
    methods: ["POST"],
    pattern: '/api/banners',
    tokens: [{"old":"/api/banners","type":0,"val":"api","end":""},{"old":"/api/banners","type":0,"val":"banners","end":""}],
    types: placeholder as Registry['banners_new.store']['types'],
  },
  'banners_new.update': {
    methods: ["PUT"],
    pattern: '/api/banners/:id',
    tokens: [{"old":"/api/banners/:id","type":0,"val":"api","end":""},{"old":"/api/banners/:id","type":0,"val":"banners","end":""},{"old":"/api/banners/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['banners_new.update']['types'],
  },
  'banners_new.destroy': {
    methods: ["DELETE"],
    pattern: '/api/banners/:id',
    tokens: [{"old":"/api/banners/:id","type":0,"val":"api","end":""},{"old":"/api/banners/:id","type":0,"val":"banners","end":""},{"old":"/api/banners/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['banners_new.destroy']['types'],
  },
  'nav_links.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/nav-links',
    tokens: [{"old":"/api/nav-links","type":0,"val":"api","end":""},{"old":"/api/nav-links","type":0,"val":"nav-links","end":""}],
    types: placeholder as Registry['nav_links.index']['types'],
  },
  'nav_links.flat': {
    methods: ["GET","HEAD"],
    pattern: '/api/nav-links/flat',
    tokens: [{"old":"/api/nav-links/flat","type":0,"val":"api","end":""},{"old":"/api/nav-links/flat","type":0,"val":"nav-links","end":""},{"old":"/api/nav-links/flat","type":0,"val":"flat","end":""}],
    types: placeholder as Registry['nav_links.flat']['types'],
  },
  'nav_links.store': {
    methods: ["POST"],
    pattern: '/api/nav-links',
    tokens: [{"old":"/api/nav-links","type":0,"val":"api","end":""},{"old":"/api/nav-links","type":0,"val":"nav-links","end":""}],
    types: placeholder as Registry['nav_links.store']['types'],
  },
  'nav_links.update': {
    methods: ["PUT"],
    pattern: '/api/nav-links/:id',
    tokens: [{"old":"/api/nav-links/:id","type":0,"val":"api","end":""},{"old":"/api/nav-links/:id","type":0,"val":"nav-links","end":""},{"old":"/api/nav-links/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['nav_links.update']['types'],
  },
  'nav_links.destroy': {
    methods: ["DELETE"],
    pattern: '/api/nav-links/:id',
    tokens: [{"old":"/api/nav-links/:id","type":0,"val":"api","end":""},{"old":"/api/nav-links/:id","type":0,"val":"nav-links","end":""},{"old":"/api/nav-links/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['nav_links.destroy']['types'],
  },
  'nav_links.reorder': {
    methods: ["POST"],
    pattern: '/api/nav-links/reorder',
    tokens: [{"old":"/api/nav-links/reorder","type":0,"val":"api","end":""},{"old":"/api/nav-links/reorder","type":0,"val":"nav-links","end":""},{"old":"/api/nav-links/reorder","type":0,"val":"reorder","end":""}],
    types: placeholder as Registry['nav_links.reorder']['types'],
  },
  'products.adjust_stock': {
    methods: ["POST"],
    pattern: '/api/products/:id/adjust-stock',
    tokens: [{"old":"/api/products/:id/adjust-stock","type":0,"val":"api","end":""},{"old":"/api/products/:id/adjust-stock","type":0,"val":"products","end":""},{"old":"/api/products/:id/adjust-stock","type":1,"val":"id","end":""},{"old":"/api/products/:id/adjust-stock","type":0,"val":"adjust-stock","end":""}],
    types: placeholder as Registry['products.adjust_stock']['types'],
  },
  'exports.leads': {
    methods: ["GET","HEAD"],
    pattern: '/api/export/leads',
    tokens: [{"old":"/api/export/leads","type":0,"val":"api","end":""},{"old":"/api/export/leads","type":0,"val":"export","end":""},{"old":"/api/export/leads","type":0,"val":"leads","end":""}],
    types: placeholder as Registry['exports.leads']['types'],
  },
  'exports.comments': {
    methods: ["GET","HEAD"],
    pattern: '/api/export/comments',
    tokens: [{"old":"/api/export/comments","type":0,"val":"api","end":""},{"old":"/api/export/comments","type":0,"val":"export","end":""},{"old":"/api/export/comments","type":0,"val":"comments","end":""}],
    types: placeholder as Registry['exports.comments']['types'],
  },
  'exports.customers': {
    methods: ["GET","HEAD"],
    pattern: '/api/export/customers',
    tokens: [{"old":"/api/export/customers","type":0,"val":"api","end":""},{"old":"/api/export/customers","type":0,"val":"export","end":""},{"old":"/api/export/customers","type":0,"val":"customers","end":""}],
    types: placeholder as Registry['exports.customers']['types'],
  },
  'exports.report': {
    methods: ["GET","HEAD"],
    pattern: '/api/export/report',
    tokens: [{"old":"/api/export/report","type":0,"val":"api","end":""},{"old":"/api/export/report","type":0,"val":"export","end":""},{"old":"/api/export/report","type":0,"val":"report","end":""}],
    types: placeholder as Registry['exports.report']['types'],
  },
  'replies.generate': {
    methods: ["POST"],
    pattern: '/api/reply/generate',
    tokens: [{"old":"/api/reply/generate","type":0,"val":"api","end":""},{"old":"/api/reply/generate","type":0,"val":"reply","end":""},{"old":"/api/reply/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['replies.generate']['types'],
  },
  'replies.sentiment': {
    methods: ["POST"],
    pattern: '/api/reply/sentiment',
    tokens: [{"old":"/api/reply/sentiment","type":0,"val":"api","end":""},{"old":"/api/reply/sentiment","type":0,"val":"reply","end":""},{"old":"/api/reply/sentiment","type":0,"val":"sentiment","end":""}],
    types: placeholder as Registry['replies.sentiment']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
