/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'master_auth.login': {
    methods: ["POST"],
    pattern: '/api/master/auth/login',
    tokens: [{"old":"/api/master/auth/login","type":0,"val":"api","end":""},{"old":"/api/master/auth/login","type":0,"val":"master","end":""},{"old":"/api/master/auth/login","type":0,"val":"auth","end":""},{"old":"/api/master/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['master_auth.login']['types'],
  },
  'master_auth.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/master/auth/me',
    tokens: [{"old":"/api/master/auth/me","type":0,"val":"api","end":""},{"old":"/api/master/auth/me","type":0,"val":"master","end":""},{"old":"/api/master/auth/me","type":0,"val":"auth","end":""},{"old":"/api/master/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['master_auth.me']['types'],
  },
  'master_auth.logout': {
    methods: ["POST"],
    pattern: '/api/master/auth/logout',
    tokens: [{"old":"/api/master/auth/logout","type":0,"val":"api","end":""},{"old":"/api/master/auth/logout","type":0,"val":"master","end":""},{"old":"/api/master/auth/logout","type":0,"val":"auth","end":""},{"old":"/api/master/auth/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['master_auth.logout']['types'],
  },
  'tenant.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/master/tenants',
    tokens: [{"old":"/api/master/tenants","type":0,"val":"api","end":""},{"old":"/api/master/tenants","type":0,"val":"master","end":""},{"old":"/api/master/tenants","type":0,"val":"tenants","end":""}],
    types: placeholder as Registry['tenant.index']['types'],
  },
  'tenant.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/master/tenants/:id',
    tokens: [{"old":"/api/master/tenants/:id","type":0,"val":"api","end":""},{"old":"/api/master/tenants/:id","type":0,"val":"master","end":""},{"old":"/api/master/tenants/:id","type":0,"val":"tenants","end":""},{"old":"/api/master/tenants/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tenant.show']['types'],
  },
  'tenant.store': {
    methods: ["POST"],
    pattern: '/api/master/tenants',
    tokens: [{"old":"/api/master/tenants","type":0,"val":"api","end":""},{"old":"/api/master/tenants","type":0,"val":"master","end":""},{"old":"/api/master/tenants","type":0,"val":"tenants","end":""}],
    types: placeholder as Registry['tenant.store']['types'],
  },
  'tenant.update': {
    methods: ["PUT"],
    pattern: '/api/master/tenants/:id',
    tokens: [{"old":"/api/master/tenants/:id","type":0,"val":"api","end":""},{"old":"/api/master/tenants/:id","type":0,"val":"master","end":""},{"old":"/api/master/tenants/:id","type":0,"val":"tenants","end":""},{"old":"/api/master/tenants/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tenant.update']['types'],
  },
  'tenant.destroy': {
    methods: ["DELETE"],
    pattern: '/api/master/tenants/:id',
    tokens: [{"old":"/api/master/tenants/:id","type":0,"val":"api","end":""},{"old":"/api/master/tenants/:id","type":0,"val":"master","end":""},{"old":"/api/master/tenants/:id","type":0,"val":"tenants","end":""},{"old":"/api/master/tenants/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['tenant.destroy']['types'],
  },
  'tenant.suspend': {
    methods: ["POST"],
    pattern: '/api/master/tenants/:id/suspend',
    tokens: [{"old":"/api/master/tenants/:id/suspend","type":0,"val":"api","end":""},{"old":"/api/master/tenants/:id/suspend","type":0,"val":"master","end":""},{"old":"/api/master/tenants/:id/suspend","type":0,"val":"tenants","end":""},{"old":"/api/master/tenants/:id/suspend","type":1,"val":"id","end":""},{"old":"/api/master/tenants/:id/suspend","type":0,"val":"suspend","end":""}],
    types: placeholder as Registry['tenant.suspend']['types'],
  },
  'tenant.activate': {
    methods: ["POST"],
    pattern: '/api/master/tenants/:id/activate',
    tokens: [{"old":"/api/master/tenants/:id/activate","type":0,"val":"api","end":""},{"old":"/api/master/tenants/:id/activate","type":0,"val":"master","end":""},{"old":"/api/master/tenants/:id/activate","type":0,"val":"tenants","end":""},{"old":"/api/master/tenants/:id/activate","type":1,"val":"id","end":""},{"old":"/api/master/tenants/:id/activate","type":0,"val":"activate","end":""}],
    types: placeholder as Registry['tenant.activate']['types'],
  },
  'tenant.migrate': {
    methods: ["POST"],
    pattern: '/api/master/tenants/:id/migrate',
    tokens: [{"old":"/api/master/tenants/:id/migrate","type":0,"val":"api","end":""},{"old":"/api/master/tenants/:id/migrate","type":0,"val":"master","end":""},{"old":"/api/master/tenants/:id/migrate","type":0,"val":"tenants","end":""},{"old":"/api/master/tenants/:id/migrate","type":1,"val":"id","end":""},{"old":"/api/master/tenants/:id/migrate","type":0,"val":"migrate","end":""}],
    types: placeholder as Registry['tenant.migrate']['types'],
  },
  'tenant.seed': {
    methods: ["POST"],
    pattern: '/api/master/tenants/:id/seed',
    tokens: [{"old":"/api/master/tenants/:id/seed","type":0,"val":"api","end":""},{"old":"/api/master/tenants/:id/seed","type":0,"val":"master","end":""},{"old":"/api/master/tenants/:id/seed","type":0,"val":"tenants","end":""},{"old":"/api/master/tenants/:id/seed","type":1,"val":"id","end":""},{"old":"/api/master/tenants/:id/seed","type":0,"val":"seed","end":""}],
    types: placeholder as Registry['tenant.seed']['types'],
  },
  'auth.register': {
    methods: ["POST"],
    pattern: '/api/auth/register',
    tokens: [{"old":"/api/auth/register","type":0,"val":"api","end":""},{"old":"/api/auth/register","type":0,"val":"auth","end":""},{"old":"/api/auth/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.register']['types'],
  },
  'auth.login': {
    methods: ["POST"],
    pattern: '/api/auth/login',
    tokens: [{"old":"/api/auth/login","type":0,"val":"api","end":""},{"old":"/api/auth/login","type":0,"val":"auth","end":""},{"old":"/api/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/me',
    tokens: [{"old":"/api/auth/me","type":0,"val":"api","end":""},{"old":"/api/auth/me","type":0,"val":"auth","end":""},{"old":"/api/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['auth.me']['types'],
  },
  'shop_auth.register': {
    methods: ["POST"],
    pattern: '/api/shop/auth/register',
    tokens: [{"old":"/api/shop/auth/register","type":0,"val":"api","end":""},{"old":"/api/shop/auth/register","type":0,"val":"shop","end":""},{"old":"/api/shop/auth/register","type":0,"val":"auth","end":""},{"old":"/api/shop/auth/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['shop_auth.register']['types'],
  },
  'shop_auth.login': {
    methods: ["POST"],
    pattern: '/api/shop/auth/login',
    tokens: [{"old":"/api/shop/auth/login","type":0,"val":"api","end":""},{"old":"/api/shop/auth/login","type":0,"val":"shop","end":""},{"old":"/api/shop/auth/login","type":0,"val":"auth","end":""},{"old":"/api/shop/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['shop_auth.login']['types'],
  },
  'shop_auth.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop/auth/me',
    tokens: [{"old":"/api/shop/auth/me","type":0,"val":"api","end":""},{"old":"/api/shop/auth/me","type":0,"val":"shop","end":""},{"old":"/api/shop/auth/me","type":0,"val":"auth","end":""},{"old":"/api/shop/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['shop_auth.me']['types'],
  },
  'shop_auth.update_profile': {
    methods: ["PUT"],
    pattern: '/api/shop/auth/profile',
    tokens: [{"old":"/api/shop/auth/profile","type":0,"val":"api","end":""},{"old":"/api/shop/auth/profile","type":0,"val":"shop","end":""},{"old":"/api/shop/auth/profile","type":0,"val":"auth","end":""},{"old":"/api/shop/auth/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['shop_auth.update_profile']['types'],
  },
  'shop_auth.change_password': {
    methods: ["PUT"],
    pattern: '/api/shop/auth/password',
    tokens: [{"old":"/api/shop/auth/password","type":0,"val":"api","end":""},{"old":"/api/shop/auth/password","type":0,"val":"shop","end":""},{"old":"/api/shop/auth/password","type":0,"val":"auth","end":""},{"old":"/api/shop/auth/password","type":0,"val":"password","end":""}],
    types: placeholder as Registry['shop_auth.change_password']['types'],
  },
  'shop_auth.forgot_password': {
    methods: ["POST"],
    pattern: '/api/shop/auth/forgot-password',
    tokens: [{"old":"/api/shop/auth/forgot-password","type":0,"val":"api","end":""},{"old":"/api/shop/auth/forgot-password","type":0,"val":"shop","end":""},{"old":"/api/shop/auth/forgot-password","type":0,"val":"auth","end":""},{"old":"/api/shop/auth/forgot-password","type":0,"val":"forgot-password","end":""}],
    types: placeholder as Registry['shop_auth.forgot_password']['types'],
  },
  'shop_auth.reset_password': {
    methods: ["POST"],
    pattern: '/api/shop/auth/reset-password',
    tokens: [{"old":"/api/shop/auth/reset-password","type":0,"val":"api","end":""},{"old":"/api/shop/auth/reset-password","type":0,"val":"shop","end":""},{"old":"/api/shop/auth/reset-password","type":0,"val":"auth","end":""},{"old":"/api/shop/auth/reset-password","type":0,"val":"reset-password","end":""}],
    types: placeholder as Registry['shop_auth.reset_password']['types'],
  },
  'storefront.products': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop/store/:storeId/products',
    tokens: [{"old":"/api/shop/store/:storeId/products","type":0,"val":"api","end":""},{"old":"/api/shop/store/:storeId/products","type":0,"val":"shop","end":""},{"old":"/api/shop/store/:storeId/products","type":0,"val":"store","end":""},{"old":"/api/shop/store/:storeId/products","type":1,"val":"storeId","end":""},{"old":"/api/shop/store/:storeId/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['storefront.products']['types'],
  },
  'storefront.product_detail': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop/store/:storeId/products/:id',
    tokens: [{"old":"/api/shop/store/:storeId/products/:id","type":0,"val":"api","end":""},{"old":"/api/shop/store/:storeId/products/:id","type":0,"val":"shop","end":""},{"old":"/api/shop/store/:storeId/products/:id","type":0,"val":"store","end":""},{"old":"/api/shop/store/:storeId/products/:id","type":1,"val":"storeId","end":""},{"old":"/api/shop/store/:storeId/products/:id","type":0,"val":"products","end":""},{"old":"/api/shop/store/:storeId/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['storefront.product_detail']['types'],
  },
  'storefront.categories': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop/store/:storeId/categories',
    tokens: [{"old":"/api/shop/store/:storeId/categories","type":0,"val":"api","end":""},{"old":"/api/shop/store/:storeId/categories","type":0,"val":"shop","end":""},{"old":"/api/shop/store/:storeId/categories","type":0,"val":"store","end":""},{"old":"/api/shop/store/:storeId/categories","type":1,"val":"storeId","end":""},{"old":"/api/shop/store/:storeId/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['storefront.categories']['types'],
  },
  'storefront.brands': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop/store/:storeId/brands',
    tokens: [{"old":"/api/shop/store/:storeId/brands","type":0,"val":"api","end":""},{"old":"/api/shop/store/:storeId/brands","type":0,"val":"shop","end":""},{"old":"/api/shop/store/:storeId/brands","type":0,"val":"store","end":""},{"old":"/api/shop/store/:storeId/brands","type":1,"val":"storeId","end":""},{"old":"/api/shop/store/:storeId/brands","type":0,"val":"brands","end":""}],
    types: placeholder as Registry['storefront.brands']['types'],
  },
  'storefront.banners': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop/store/:storeId/banners',
    tokens: [{"old":"/api/shop/store/:storeId/banners","type":0,"val":"api","end":""},{"old":"/api/shop/store/:storeId/banners","type":0,"val":"shop","end":""},{"old":"/api/shop/store/:storeId/banners","type":0,"val":"store","end":""},{"old":"/api/shop/store/:storeId/banners","type":1,"val":"storeId","end":""},{"old":"/api/shop/store/:storeId/banners","type":0,"val":"banners","end":""}],
    types: placeholder as Registry['storefront.banners']['types'],
  },
  'storefront.pages': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop/store/:storeId/pages',
    tokens: [{"old":"/api/shop/store/:storeId/pages","type":0,"val":"api","end":""},{"old":"/api/shop/store/:storeId/pages","type":0,"val":"shop","end":""},{"old":"/api/shop/store/:storeId/pages","type":0,"val":"store","end":""},{"old":"/api/shop/store/:storeId/pages","type":1,"val":"storeId","end":""},{"old":"/api/shop/store/:storeId/pages","type":0,"val":"pages","end":""}],
    types: placeholder as Registry['storefront.pages']['types'],
  },
  'storefront.page_detail': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop/store/:storeId/pages/:id',
    tokens: [{"old":"/api/shop/store/:storeId/pages/:id","type":0,"val":"api","end":""},{"old":"/api/shop/store/:storeId/pages/:id","type":0,"val":"shop","end":""},{"old":"/api/shop/store/:storeId/pages/:id","type":0,"val":"store","end":""},{"old":"/api/shop/store/:storeId/pages/:id","type":1,"val":"storeId","end":""},{"old":"/api/shop/store/:storeId/pages/:id","type":0,"val":"pages","end":""},{"old":"/api/shop/store/:storeId/pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['storefront.page_detail']['types'],
  },
  'storefront.store_info': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop/store/:storeId/info',
    tokens: [{"old":"/api/shop/store/:storeId/info","type":0,"val":"api","end":""},{"old":"/api/shop/store/:storeId/info","type":0,"val":"shop","end":""},{"old":"/api/shop/store/:storeId/info","type":0,"val":"store","end":""},{"old":"/api/shop/store/:storeId/info","type":1,"val":"storeId","end":""},{"old":"/api/shop/store/:storeId/info","type":0,"val":"info","end":""}],
    types: placeholder as Registry['storefront.store_info']['types'],
  },
  'shops.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/shops',
    tokens: [{"old":"/api/shops","type":0,"val":"api","end":""},{"old":"/api/shops","type":0,"val":"shops","end":""}],
    types: placeholder as Registry['shops.index']['types'],
  },
  'shops.store': {
    methods: ["POST"],
    pattern: '/api/shops',
    tokens: [{"old":"/api/shops","type":0,"val":"api","end":""},{"old":"/api/shops","type":0,"val":"shops","end":""}],
    types: placeholder as Registry['shops.store']['types'],
  },
  'shops.find_or_create': {
    methods: ["POST"],
    pattern: '/api/shops/find-or-create',
    tokens: [{"old":"/api/shops/find-or-create","type":0,"val":"api","end":""},{"old":"/api/shops/find-or-create","type":0,"val":"shops","end":""},{"old":"/api/shops/find-or-create","type":0,"val":"find-or-create","end":""}],
    types: placeholder as Registry['shops.find_or_create']['types'],
  },
  'shops.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/shops/:id',
    tokens: [{"old":"/api/shops/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shops.show']['types'],
  },
  'shops.update': {
    methods: ["PUT"],
    pattern: '/api/shops/:id',
    tokens: [{"old":"/api/shops/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shops.update']['types'],
  },
  'shops.destroy': {
    methods: ["DELETE"],
    pattern: '/api/shops/:id',
    tokens: [{"old":"/api/shops/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shops.destroy']['types'],
  },
  'keywords.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/shops/:shopId/keywords',
    tokens: [{"old":"/api/shops/:shopId/keywords","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/keywords","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/keywords","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/keywords","type":0,"val":"keywords","end":""}],
    types: placeholder as Registry['keywords.index']['types'],
  },
  'keywords.store': {
    methods: ["POST"],
    pattern: '/api/shops/:shopId/keywords',
    tokens: [{"old":"/api/shops/:shopId/keywords","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/keywords","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/keywords","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/keywords","type":0,"val":"keywords","end":""}],
    types: placeholder as Registry['keywords.store']['types'],
  },
  'keywords.destroy': {
    methods: ["DELETE"],
    pattern: '/api/shops/:shopId/keywords/:id',
    tokens: [{"old":"/api/shops/:shopId/keywords/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/keywords/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/keywords/:id","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/keywords/:id","type":0,"val":"keywords","end":""},{"old":"/api/shops/:shopId/keywords/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['keywords.destroy']['types'],
  },
  'templates.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/shops/:shopId/templates',
    tokens: [{"old":"/api/shops/:shopId/templates","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/templates","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/templates","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['templates.index']['types'],
  },
  'templates.store': {
    methods: ["POST"],
    pattern: '/api/shops/:shopId/templates',
    tokens: [{"old":"/api/shops/:shopId/templates","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/templates","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/templates","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['templates.store']['types'],
  },
  'templates.destroy': {
    methods: ["DELETE"],
    pattern: '/api/shops/:shopId/templates/:id',
    tokens: [{"old":"/api/shops/:shopId/templates/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/templates/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/templates/:id","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/templates/:id","type":0,"val":"templates","end":""},{"old":"/api/shops/:shopId/templates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['templates.destroy']['types'],
  },
  'products.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/products',
    tokens: [{"old":"/api/products","type":0,"val":"api","end":""},{"old":"/api/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.index']['types'],
  },
  'products.store': {
    methods: ["POST"],
    pattern: '/api/products',
    tokens: [{"old":"/api/products","type":0,"val":"api","end":""},{"old":"/api/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.store']['types'],
  },
  'products.update': {
    methods: ["PUT"],
    pattern: '/api/products/:id',
    tokens: [{"old":"/api/products/:id","type":0,"val":"api","end":""},{"old":"/api/products/:id","type":0,"val":"products","end":""},{"old":"/api/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.update']['types'],
  },
  'products.destroy': {
    methods: ["DELETE"],
    pattern: '/api/products/:id',
    tokens: [{"old":"/api/products/:id","type":0,"val":"api","end":""},{"old":"/api/products/:id","type":0,"val":"products","end":""},{"old":"/api/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.destroy']['types'],
  },
  'categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/categories',
    tokens: [{"old":"/api/categories","type":0,"val":"api","end":""},{"old":"/api/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['categories.index']['types'],
  },
  'categories.store': {
    methods: ["POST"],
    pattern: '/api/categories',
    tokens: [{"old":"/api/categories","type":0,"val":"api","end":""},{"old":"/api/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['categories.store']['types'],
  },
  'categories.update': {
    methods: ["PUT"],
    pattern: '/api/categories/:id',
    tokens: [{"old":"/api/categories/:id","type":0,"val":"api","end":""},{"old":"/api/categories/:id","type":0,"val":"categories","end":""},{"old":"/api/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categories.update']['types'],
  },
  'categories.destroy': {
    methods: ["DELETE"],
    pattern: '/api/categories/:id',
    tokens: [{"old":"/api/categories/:id","type":0,"val":"api","end":""},{"old":"/api/categories/:id","type":0,"val":"categories","end":""},{"old":"/api/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['categories.destroy']['types'],
  },
  'brands.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/brands',
    tokens: [{"old":"/api/brands","type":0,"val":"api","end":""},{"old":"/api/brands","type":0,"val":"brands","end":""}],
    types: placeholder as Registry['brands.index']['types'],
  },
  'brands.store': {
    methods: ["POST"],
    pattern: '/api/brands',
    tokens: [{"old":"/api/brands","type":0,"val":"api","end":""},{"old":"/api/brands","type":0,"val":"brands","end":""}],
    types: placeholder as Registry['brands.store']['types'],
  },
  'brands.update': {
    methods: ["PUT"],
    pattern: '/api/brands/:id',
    tokens: [{"old":"/api/brands/:id","type":0,"val":"api","end":""},{"old":"/api/brands/:id","type":0,"val":"brands","end":""},{"old":"/api/brands/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['brands.update']['types'],
  },
  'brands.destroy': {
    methods: ["DELETE"],
    pattern: '/api/brands/:id',
    tokens: [{"old":"/api/brands/:id","type":0,"val":"api","end":""},{"old":"/api/brands/:id","type":0,"val":"brands","end":""},{"old":"/api/brands/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['brands.destroy']['types'],
  },
  'leads.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/leads',
    tokens: [{"old":"/api/leads","type":0,"val":"api","end":""},{"old":"/api/leads","type":0,"val":"leads","end":""}],
    types: placeholder as Registry['leads.index']['types'],
  },
  'leads.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/leads/stats',
    tokens: [{"old":"/api/leads/stats","type":0,"val":"api","end":""},{"old":"/api/leads/stats","type":0,"val":"leads","end":""},{"old":"/api/leads/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['leads.stats']['types'],
  },
  'leads.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/leads/:id',
    tokens: [{"old":"/api/leads/:id","type":0,"val":"api","end":""},{"old":"/api/leads/:id","type":0,"val":"leads","end":""},{"old":"/api/leads/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leads.show']['types'],
  },
  'leads.update': {
    methods: ["PUT"],
    pattern: '/api/leads/:id',
    tokens: [{"old":"/api/leads/:id","type":0,"val":"api","end":""},{"old":"/api/leads/:id","type":0,"val":"leads","end":""},{"old":"/api/leads/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leads.update']['types'],
  },
  'leads.destroy': {
    methods: ["DELETE"],
    pattern: '/api/leads/:id',
    tokens: [{"old":"/api/leads/:id","type":0,"val":"api","end":""},{"old":"/api/leads/:id","type":0,"val":"leads","end":""},{"old":"/api/leads/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leads.destroy']['types'],
  },
  'leads.pipeline_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/leads-pipeline',
    tokens: [{"old":"/api/leads-pipeline","type":0,"val":"api","end":""},{"old":"/api/leads-pipeline","type":0,"val":"leads-pipeline","end":""}],
    types: placeholder as Registry['leads.pipeline_stats']['types'],
  },
  'dashboard.overview': {
    methods: ["GET","HEAD"],
    pattern: '/api/dashboard/overview',
    tokens: [{"old":"/api/dashboard/overview","type":0,"val":"api","end":""},{"old":"/api/dashboard/overview","type":0,"val":"dashboard","end":""},{"old":"/api/dashboard/overview","type":0,"val":"overview","end":""}],
    types: placeholder as Registry['dashboard.overview']['types'],
  },
  'dashboard.recent_leads': {
    methods: ["GET","HEAD"],
    pattern: '/api/dashboard/recent-leads',
    tokens: [{"old":"/api/dashboard/recent-leads","type":0,"val":"api","end":""},{"old":"/api/dashboard/recent-leads","type":0,"val":"dashboard","end":""},{"old":"/api/dashboard/recent-leads","type":0,"val":"recent-leads","end":""}],
    types: placeholder as Registry['dashboard.recent_leads']['types'],
  },
  'dashboard.analytics': {
    methods: ["GET","HEAD"],
    pattern: '/api/dashboard/analytics',
    tokens: [{"old":"/api/dashboard/analytics","type":0,"val":"api","end":""},{"old":"/api/dashboard/analytics","type":0,"val":"dashboard","end":""},{"old":"/api/dashboard/analytics","type":0,"val":"analytics","end":""}],
    types: placeholder as Registry['dashboard.analytics']['types'],
  },
  'dashboard.top_customers': {
    methods: ["GET","HEAD"],
    pattern: '/api/dashboard/top-customers',
    tokens: [{"old":"/api/dashboard/top-customers","type":0,"val":"api","end":""},{"old":"/api/dashboard/top-customers","type":0,"val":"dashboard","end":""},{"old":"/api/dashboard/top-customers","type":0,"val":"top-customers","end":""}],
    types: placeholder as Registry['dashboard.top_customers']['types'],
  },
  'dashboard.order_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/dashboard/order-stats',
    tokens: [{"old":"/api/dashboard/order-stats","type":0,"val":"api","end":""},{"old":"/api/dashboard/order-stats","type":0,"val":"dashboard","end":""},{"old":"/api/dashboard/order-stats","type":0,"val":"order-stats","end":""}],
    types: placeholder as Registry['dashboard.order_stats']['types'],
  },
  'analytics.daily': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/daily',
    tokens: [{"old":"/api/analytics/daily","type":0,"val":"api","end":""},{"old":"/api/analytics/daily","type":0,"val":"analytics","end":""},{"old":"/api/analytics/daily","type":0,"val":"daily","end":""}],
    types: placeholder as Registry['analytics.daily']['types'],
  },
  'analytics.hourly': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/hourly',
    tokens: [{"old":"/api/analytics/hourly","type":0,"val":"api","end":""},{"old":"/api/analytics/hourly","type":0,"val":"analytics","end":""},{"old":"/api/analytics/hourly","type":0,"val":"hourly","end":""}],
    types: placeholder as Registry['analytics.hourly']['types'],
  },
  'analytics.conversion': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/conversion',
    tokens: [{"old":"/api/analytics/conversion","type":0,"val":"api","end":""},{"old":"/api/analytics/conversion","type":0,"val":"analytics","end":""},{"old":"/api/analytics/conversion","type":0,"val":"conversion","end":""}],
    types: placeholder as Registry['analytics.conversion']['types'],
  },
  'analytics.top_keywords': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/top-keywords',
    tokens: [{"old":"/api/analytics/top-keywords","type":0,"val":"api","end":""},{"old":"/api/analytics/top-keywords","type":0,"val":"analytics","end":""},{"old":"/api/analytics/top-keywords","type":0,"val":"top-keywords","end":""}],
    types: placeholder as Registry['analytics.top_keywords']['types'],
  },
  'analytics.summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/summary',
    tokens: [{"old":"/api/analytics/summary","type":0,"val":"api","end":""},{"old":"/api/analytics/summary","type":0,"val":"analytics","end":""},{"old":"/api/analytics/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['analytics.summary']['types'],
  },
  'analytics.revenue': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/revenue',
    tokens: [{"old":"/api/analytics/revenue","type":0,"val":"api","end":""},{"old":"/api/analytics/revenue","type":0,"val":"analytics","end":""},{"old":"/api/analytics/revenue","type":0,"val":"revenue","end":""}],
    types: placeholder as Registry['analytics.revenue']['types'],
  },
  'notifications.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/notifications',
    tokens: [{"old":"/api/notifications","type":0,"val":"api","end":""},{"old":"/api/notifications","type":0,"val":"notifications","end":""}],
    types: placeholder as Registry['notifications.index']['types'],
  },
  'notifications.unread_count': {
    methods: ["GET","HEAD"],
    pattern: '/api/notifications/unread-count',
    tokens: [{"old":"/api/notifications/unread-count","type":0,"val":"api","end":""},{"old":"/api/notifications/unread-count","type":0,"val":"notifications","end":""},{"old":"/api/notifications/unread-count","type":0,"val":"unread-count","end":""}],
    types: placeholder as Registry['notifications.unread_count']['types'],
  },
  'notifications.mark_read': {
    methods: ["PUT"],
    pattern: '/api/notifications/:id/read',
    tokens: [{"old":"/api/notifications/:id/read","type":0,"val":"api","end":""},{"old":"/api/notifications/:id/read","type":0,"val":"notifications","end":""},{"old":"/api/notifications/:id/read","type":1,"val":"id","end":""},{"old":"/api/notifications/:id/read","type":0,"val":"read","end":""}],
    types: placeholder as Registry['notifications.mark_read']['types'],
  },
  'notifications.mark_all_read': {
    methods: ["PUT"],
    pattern: '/api/notifications/read-all',
    tokens: [{"old":"/api/notifications/read-all","type":0,"val":"api","end":""},{"old":"/api/notifications/read-all","type":0,"val":"notifications","end":""},{"old":"/api/notifications/read-all","type":0,"val":"read-all","end":""}],
    types: placeholder as Registry['notifications.mark_all_read']['types'],
  },
  'customers.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/customers',
    tokens: [{"old":"/api/customers","type":0,"val":"api","end":""},{"old":"/api/customers","type":0,"val":"customers","end":""}],
    types: placeholder as Registry['customers.index']['types'],
  },
  'customers.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/customers/:id',
    tokens: [{"old":"/api/customers/:id","type":0,"val":"api","end":""},{"old":"/api/customers/:id","type":0,"val":"customers","end":""},{"old":"/api/customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['customers.show']['types'],
  },
  'customers.update': {
    methods: ["PUT"],
    pattern: '/api/customers/:id',
    tokens: [{"old":"/api/customers/:id","type":0,"val":"api","end":""},{"old":"/api/customers/:id","type":0,"val":"customers","end":""},{"old":"/api/customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['customers.update']['types'],
  },
  'customers.destroy': {
    methods: ["DELETE"],
    pattern: '/api/customers/:id',
    tokens: [{"old":"/api/customers/:id","type":0,"val":"api","end":""},{"old":"/api/customers/:id","type":0,"val":"customers","end":""},{"old":"/api/customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['customers.destroy']['types'],
  },
  'sessions.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/sessions',
    tokens: [{"old":"/api/sessions","type":0,"val":"api","end":""},{"old":"/api/sessions","type":0,"val":"sessions","end":""}],
    types: placeholder as Registry['sessions.index']['types'],
  },
  'sessions.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/sessions/:id',
    tokens: [{"old":"/api/sessions/:id","type":0,"val":"api","end":""},{"old":"/api/sessions/:id","type":0,"val":"sessions","end":""},{"old":"/api/sessions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['sessions.show']['types'],
  },
  'orders.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders',
    tokens: [{"old":"/api/orders","type":0,"val":"api","end":""},{"old":"/api/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['orders.index']['types'],
  },
  'orders.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders/stats',
    tokens: [{"old":"/api/orders/stats","type":0,"val":"api","end":""},{"old":"/api/orders/stats","type":0,"val":"orders","end":""},{"old":"/api/orders/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['orders.stats']['types'],
  },
  'orders.store': {
    methods: ["POST"],
    pattern: '/api/orders',
    tokens: [{"old":"/api/orders","type":0,"val":"api","end":""},{"old":"/api/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['orders.store']['types'],
  },
  'orders.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders/:id',
    tokens: [{"old":"/api/orders/:id","type":0,"val":"api","end":""},{"old":"/api/orders/:id","type":0,"val":"orders","end":""},{"old":"/api/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['orders.show']['types'],
  },
  'orders.update': {
    methods: ["PUT"],
    pattern: '/api/orders/:id',
    tokens: [{"old":"/api/orders/:id","type":0,"val":"api","end":""},{"old":"/api/orders/:id","type":0,"val":"orders","end":""},{"old":"/api/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['orders.update']['types'],
  },
  'orders.destroy': {
    methods: ["DELETE"],
    pattern: '/api/orders/:id',
    tokens: [{"old":"/api/orders/:id","type":0,"val":"api","end":""},{"old":"/api/orders/:id","type":0,"val":"orders","end":""},{"old":"/api/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['orders.destroy']['types'],
  },
  'orders.get_details': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders/:id/details',
    tokens: [{"old":"/api/orders/:id/details","type":0,"val":"api","end":""},{"old":"/api/orders/:id/details","type":0,"val":"orders","end":""},{"old":"/api/orders/:id/details","type":1,"val":"id","end":""},{"old":"/api/orders/:id/details","type":0,"val":"details","end":""}],
    types: placeholder as Registry['orders.get_details']['types'],
  },
  'orders.get_totals': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders/:id/totals',
    tokens: [{"old":"/api/orders/:id/totals","type":0,"val":"api","end":""},{"old":"/api/orders/:id/totals","type":0,"val":"orders","end":""},{"old":"/api/orders/:id/totals","type":1,"val":"id","end":""},{"old":"/api/orders/:id/totals","type":0,"val":"totals","end":""}],
    types: placeholder as Registry['orders.get_totals']['types'],
  },
  'orders.get_history': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders/:id/history',
    tokens: [{"old":"/api/orders/:id/history","type":0,"val":"api","end":""},{"old":"/api/orders/:id/history","type":0,"val":"orders","end":""},{"old":"/api/orders/:id/history","type":1,"val":"id","end":""},{"old":"/api/orders/:id/history","type":0,"val":"history","end":""}],
    types: placeholder as Registry['orders.get_history']['types'],
  },
  'orders.update_status': {
    methods: ["PUT"],
    pattern: '/api/orders/:id/status',
    tokens: [{"old":"/api/orders/:id/status","type":0,"val":"api","end":""},{"old":"/api/orders/:id/status","type":0,"val":"orders","end":""},{"old":"/api/orders/:id/status","type":1,"val":"id","end":""},{"old":"/api/orders/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['orders.update_status']['types'],
  },
  'orders.get_order_statuses': {
    methods: ["GET","HEAD"],
    pattern: '/api/order-statuses',
    tokens: [{"old":"/api/order-statuses","type":0,"val":"api","end":""},{"old":"/api/order-statuses","type":0,"val":"order-statuses","end":""}],
    types: placeholder as Registry['orders.get_order_statuses']['types'],
  },
  'orders.get_payment_statuses': {
    methods: ["GET","HEAD"],
    pattern: '/api/payment-statuses',
    tokens: [{"old":"/api/payment-statuses","type":0,"val":"api","end":""},{"old":"/api/payment-statuses","type":0,"val":"payment-statuses","end":""}],
    types: placeholder as Registry['orders.get_payment_statuses']['types'],
  },
  'carts.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/cart',
    tokens: [{"old":"/api/cart","type":0,"val":"api","end":""},{"old":"/api/cart","type":0,"val":"cart","end":""}],
    types: placeholder as Registry['carts.show']['types'],
  },
  'carts.add_item': {
    methods: ["POST"],
    pattern: '/api/cart/items',
    tokens: [{"old":"/api/cart/items","type":0,"val":"api","end":""},{"old":"/api/cart/items","type":0,"val":"cart","end":""},{"old":"/api/cart/items","type":0,"val":"items","end":""}],
    types: placeholder as Registry['carts.add_item']['types'],
  },
  'carts.update_item': {
    methods: ["PUT"],
    pattern: '/api/cart/items/:productId',
    tokens: [{"old":"/api/cart/items/:productId","type":0,"val":"api","end":""},{"old":"/api/cart/items/:productId","type":0,"val":"cart","end":""},{"old":"/api/cart/items/:productId","type":0,"val":"items","end":""},{"old":"/api/cart/items/:productId","type":1,"val":"productId","end":""}],
    types: placeholder as Registry['carts.update_item']['types'],
  },
  'carts.remove_item': {
    methods: ["DELETE"],
    pattern: '/api/cart/items/:productId',
    tokens: [{"old":"/api/cart/items/:productId","type":0,"val":"api","end":""},{"old":"/api/cart/items/:productId","type":0,"val":"cart","end":""},{"old":"/api/cart/items/:productId","type":0,"val":"items","end":""},{"old":"/api/cart/items/:productId","type":1,"val":"productId","end":""}],
    types: placeholder as Registry['carts.remove_item']['types'],
  },
  'carts.checkout': {
    methods: ["POST"],
    pattern: '/api/cart/checkout',
    tokens: [{"old":"/api/cart/checkout","type":0,"val":"api","end":""},{"old":"/api/cart/checkout","type":0,"val":"cart","end":""},{"old":"/api/cart/checkout","type":0,"val":"checkout","end":""}],
    types: placeholder as Registry['carts.checkout']['types'],
  },
  'schedules.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/schedules',
    tokens: [{"old":"/api/schedules","type":0,"val":"api","end":""},{"old":"/api/schedules","type":0,"val":"schedules","end":""}],
    types: placeholder as Registry['schedules.index']['types'],
  },
  'schedules.store': {
    methods: ["POST"],
    pattern: '/api/schedules',
    tokens: [{"old":"/api/schedules","type":0,"val":"api","end":""},{"old":"/api/schedules","type":0,"val":"schedules","end":""}],
    types: placeholder as Registry['schedules.store']['types'],
  },
  'schedules.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/schedules/:id',
    tokens: [{"old":"/api/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['schedules.show']['types'],
  },
  'schedules.update': {
    methods: ["PUT"],
    pattern: '/api/schedules/:id',
    tokens: [{"old":"/api/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['schedules.update']['types'],
  },
  'schedules.destroy': {
    methods: ["DELETE"],
    pattern: '/api/schedules/:id',
    tokens: [{"old":"/api/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['schedules.destroy']['types'],
  },
  'shop_customers.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop-customers',
    tokens: [{"old":"/api/shop-customers","type":0,"val":"api","end":""},{"old":"/api/shop-customers","type":0,"val":"shop-customers","end":""}],
    types: placeholder as Registry['shop_customers.index']['types'],
  },
  'shop_customers.store': {
    methods: ["POST"],
    pattern: '/api/shop-customers',
    tokens: [{"old":"/api/shop-customers","type":0,"val":"api","end":""},{"old":"/api/shop-customers","type":0,"val":"shop-customers","end":""}],
    types: placeholder as Registry['shop_customers.store']['types'],
  },
  'shop_customers.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop-customers/:id',
    tokens: [{"old":"/api/shop-customers/:id","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:id","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shop_customers.show']['types'],
  },
  'shop_customers.update': {
    methods: ["PUT"],
    pattern: '/api/shop-customers/:id',
    tokens: [{"old":"/api/shop-customers/:id","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:id","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shop_customers.update']['types'],
  },
  'shop_customers.destroy': {
    methods: ["DELETE"],
    pattern: '/api/shop-customers/:id',
    tokens: [{"old":"/api/shop-customers/:id","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:id","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shop_customers.destroy']['types'],
  },
  'shop_customers.list_addresses': {
    methods: ["GET","HEAD"],
    pattern: '/api/shop-customers/:customerId/addresses',
    tokens: [{"old":"/api/shop-customers/:customerId/addresses","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:customerId/addresses","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:customerId/addresses","type":1,"val":"customerId","end":""},{"old":"/api/shop-customers/:customerId/addresses","type":0,"val":"addresses","end":""}],
    types: placeholder as Registry['shop_customers.list_addresses']['types'],
  },
  'shop_customers.add_address': {
    methods: ["POST"],
    pattern: '/api/shop-customers/:customerId/addresses',
    tokens: [{"old":"/api/shop-customers/:customerId/addresses","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:customerId/addresses","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:customerId/addresses","type":1,"val":"customerId","end":""},{"old":"/api/shop-customers/:customerId/addresses","type":0,"val":"addresses","end":""}],
    types: placeholder as Registry['shop_customers.add_address']['types'],
  },
  'shop_customers.update_address': {
    methods: ["PUT"],
    pattern: '/api/shop-customers/:customerId/addresses/:id',
    tokens: [{"old":"/api/shop-customers/:customerId/addresses/:id","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":1,"val":"customerId","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":0,"val":"addresses","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shop_customers.update_address']['types'],
  },
  'shop_customers.delete_address': {
    methods: ["DELETE"],
    pattern: '/api/shop-customers/:customerId/addresses/:id',
    tokens: [{"old":"/api/shop-customers/:customerId/addresses/:id","type":0,"val":"api","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":0,"val":"shop-customers","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":1,"val":"customerId","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":0,"val":"addresses","end":""},{"old":"/api/shop-customers/:customerId/addresses/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shop_customers.delete_address']['types'],
  },
  'promotions.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/promotions',
    tokens: [{"old":"/api/promotions","type":0,"val":"api","end":""},{"old":"/api/promotions","type":0,"val":"promotions","end":""}],
    types: placeholder as Registry['promotions.index']['types'],
  },
  'promotions.store': {
    methods: ["POST"],
    pattern: '/api/promotions',
    tokens: [{"old":"/api/promotions","type":0,"val":"api","end":""},{"old":"/api/promotions","type":0,"val":"promotions","end":""}],
    types: placeholder as Registry['promotions.store']['types'],
  },
  'promotions.destroy_promotion': {
    methods: ["DELETE"],
    pattern: '/api/promotions/:productId',
    tokens: [{"old":"/api/promotions/:productId","type":0,"val":"api","end":""},{"old":"/api/promotions/:productId","type":0,"val":"promotions","end":""},{"old":"/api/promotions/:productId","type":1,"val":"productId","end":""}],
    types: placeholder as Registry['promotions.destroy_promotion']['types'],
  },
  'promotions.list_coupons': {
    methods: ["GET","HEAD"],
    pattern: '/api/coupons',
    tokens: [{"old":"/api/coupons","type":0,"val":"api","end":""},{"old":"/api/coupons","type":0,"val":"coupons","end":""}],
    types: placeholder as Registry['promotions.list_coupons']['types'],
  },
  'promotions.store_coupon': {
    methods: ["POST"],
    pattern: '/api/coupons',
    tokens: [{"old":"/api/coupons","type":0,"val":"api","end":""},{"old":"/api/coupons","type":0,"val":"coupons","end":""}],
    types: placeholder as Registry['promotions.store_coupon']['types'],
  },
  'promotions.update_coupon': {
    methods: ["PUT"],
    pattern: '/api/coupons/:id',
    tokens: [{"old":"/api/coupons/:id","type":0,"val":"api","end":""},{"old":"/api/coupons/:id","type":0,"val":"coupons","end":""},{"old":"/api/coupons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['promotions.update_coupon']['types'],
  },
  'promotions.destroy_coupon': {
    methods: ["DELETE"],
    pattern: '/api/coupons/:id',
    tokens: [{"old":"/api/coupons/:id","type":0,"val":"api","end":""},{"old":"/api/coupons/:id","type":0,"val":"coupons","end":""},{"old":"/api/coupons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['promotions.destroy_coupon']['types'],
  },
  'promotions.validate_coupon': {
    methods: ["POST"],
    pattern: '/api/coupons/validate',
    tokens: [{"old":"/api/coupons/validate","type":0,"val":"api","end":""},{"old":"/api/coupons/validate","type":0,"val":"coupons","end":""},{"old":"/api/coupons/validate","type":0,"val":"validate","end":""}],
    types: placeholder as Registry['promotions.validate_coupon']['types'],
  },
  'cms_pages.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/cms-pages',
    tokens: [{"old":"/api/cms-pages","type":0,"val":"api","end":""},{"old":"/api/cms-pages","type":0,"val":"cms-pages","end":""}],
    types: placeholder as Registry['cms_pages.index']['types'],
  },
  'cms_pages.store': {
    methods: ["POST"],
    pattern: '/api/cms-pages',
    tokens: [{"old":"/api/cms-pages","type":0,"val":"api","end":""},{"old":"/api/cms-pages","type":0,"val":"cms-pages","end":""}],
    types: placeholder as Registry['cms_pages.store']['types'],
  },
  'cms_pages.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/cms-pages/:id',
    tokens: [{"old":"/api/cms-pages/:id","type":0,"val":"api","end":""},{"old":"/api/cms-pages/:id","type":0,"val":"cms-pages","end":""},{"old":"/api/cms-pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cms_pages.show']['types'],
  },
  'cms_pages.update': {
    methods: ["PUT"],
    pattern: '/api/cms-pages/:id',
    tokens: [{"old":"/api/cms-pages/:id","type":0,"val":"api","end":""},{"old":"/api/cms-pages/:id","type":0,"val":"cms-pages","end":""},{"old":"/api/cms-pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cms_pages.update']['types'],
  },
  'cms_pages.destroy': {
    methods: ["DELETE"],
    pattern: '/api/cms-pages/:id',
    tokens: [{"old":"/api/cms-pages/:id","type":0,"val":"api","end":""},{"old":"/api/cms-pages/:id","type":0,"val":"cms-pages","end":""},{"old":"/api/cms-pages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['cms_pages.destroy']['types'],
  },
  'banners_new.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/banners',
    tokens: [{"old":"/api/banners","type":0,"val":"api","end":""},{"old":"/api/banners","type":0,"val":"banners","end":""}],
    types: placeholder as Registry['banners_new.index']['types'],
  },
  'banners_new.store': {
    methods: ["POST"],
    pattern: '/api/banners',
    tokens: [{"old":"/api/banners","type":0,"val":"api","end":""},{"old":"/api/banners","type":0,"val":"banners","end":""}],
    types: placeholder as Registry['banners_new.store']['types'],
  },
  'banners_new.update': {
    methods: ["PUT"],
    pattern: '/api/banners/:id',
    tokens: [{"old":"/api/banners/:id","type":0,"val":"api","end":""},{"old":"/api/banners/:id","type":0,"val":"banners","end":""},{"old":"/api/banners/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['banners_new.update']['types'],
  },
  'banners_new.destroy': {
    methods: ["DELETE"],
    pattern: '/api/banners/:id',
    tokens: [{"old":"/api/banners/:id","type":0,"val":"api","end":""},{"old":"/api/banners/:id","type":0,"val":"banners","end":""},{"old":"/api/banners/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['banners_new.destroy']['types'],
  },
  'nav_links.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/nav-links',
    tokens: [{"old":"/api/nav-links","type":0,"val":"api","end":""},{"old":"/api/nav-links","type":0,"val":"nav-links","end":""}],
    types: placeholder as Registry['nav_links.index']['types'],
  },
  'nav_links.flat': {
    methods: ["GET","HEAD"],
    pattern: '/api/nav-links/flat',
    tokens: [{"old":"/api/nav-links/flat","type":0,"val":"api","end":""},{"old":"/api/nav-links/flat","type":0,"val":"nav-links","end":""},{"old":"/api/nav-links/flat","type":0,"val":"flat","end":""}],
    types: placeholder as Registry['nav_links.flat']['types'],
  },
  'nav_links.store': {
    methods: ["POST"],
    pattern: '/api/nav-links',
    tokens: [{"old":"/api/nav-links","type":0,"val":"api","end":""},{"old":"/api/nav-links","type":0,"val":"nav-links","end":""}],
    types: placeholder as Registry['nav_links.store']['types'],
  },
  'nav_links.update': {
    methods: ["PUT"],
    pattern: '/api/nav-links/:id',
    tokens: [{"old":"/api/nav-links/:id","type":0,"val":"api","end":""},{"old":"/api/nav-links/:id","type":0,"val":"nav-links","end":""},{"old":"/api/nav-links/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['nav_links.update']['types'],
  },
  'nav_links.destroy': {
    methods: ["DELETE"],
    pattern: '/api/nav-links/:id',
    tokens: [{"old":"/api/nav-links/:id","type":0,"val":"api","end":""},{"old":"/api/nav-links/:id","type":0,"val":"nav-links","end":""},{"old":"/api/nav-links/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['nav_links.destroy']['types'],
  },
  'nav_links.reorder': {
    methods: ["POST"],
    pattern: '/api/nav-links/reorder',
    tokens: [{"old":"/api/nav-links/reorder","type":0,"val":"api","end":""},{"old":"/api/nav-links/reorder","type":0,"val":"nav-links","end":""},{"old":"/api/nav-links/reorder","type":0,"val":"reorder","end":""}],
    types: placeholder as Registry['nav_links.reorder']['types'],
  },
  'webhooks.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/webhooks',
    tokens: [{"old":"/api/webhooks","type":0,"val":"api","end":""},{"old":"/api/webhooks","type":0,"val":"webhooks","end":""}],
    types: placeholder as Registry['webhooks.index']['types'],
  },
  'webhooks.store': {
    methods: ["POST"],
    pattern: '/api/webhooks',
    tokens: [{"old":"/api/webhooks","type":0,"val":"api","end":""},{"old":"/api/webhooks","type":0,"val":"webhooks","end":""}],
    types: placeholder as Registry['webhooks.store']['types'],
  },
  'webhooks.update': {
    methods: ["PUT"],
    pattern: '/api/webhooks/:id',
    tokens: [{"old":"/api/webhooks/:id","type":0,"val":"api","end":""},{"old":"/api/webhooks/:id","type":0,"val":"webhooks","end":""},{"old":"/api/webhooks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['webhooks.update']['types'],
  },
  'webhooks.destroy': {
    methods: ["DELETE"],
    pattern: '/api/webhooks/:id',
    tokens: [{"old":"/api/webhooks/:id","type":0,"val":"api","end":""},{"old":"/api/webhooks/:id","type":0,"val":"webhooks","end":""},{"old":"/api/webhooks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['webhooks.destroy']['types'],
  },
  'activity_logs.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/activity-logs',
    tokens: [{"old":"/api/activity-logs","type":0,"val":"api","end":""},{"old":"/api/activity-logs","type":0,"val":"activity-logs","end":""}],
    types: placeholder as Registry['activity_logs.index']['types'],
  },
  'activity_logs.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/activity-logs/stats',
    tokens: [{"old":"/api/activity-logs/stats","type":0,"val":"api","end":""},{"old":"/api/activity-logs/stats","type":0,"val":"activity-logs","end":""},{"old":"/api/activity-logs/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['activity_logs.stats']['types'],
  },
  'activity_logs.entity_types': {
    methods: ["GET","HEAD"],
    pattern: '/api/activity-logs/entity-types',
    tokens: [{"old":"/api/activity-logs/entity-types","type":0,"val":"api","end":""},{"old":"/api/activity-logs/entity-types","type":0,"val":"activity-logs","end":""},{"old":"/api/activity-logs/entity-types","type":0,"val":"entity-types","end":""}],
    types: placeholder as Registry['activity_logs.entity_types']['types'],
  },
  'roles.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/roles',
    tokens: [{"old":"/api/roles","type":0,"val":"api","end":""},{"old":"/api/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.index']['types'],
  },
  'roles.permissions': {
    methods: ["GET","HEAD"],
    pattern: '/api/roles/permissions',
    tokens: [{"old":"/api/roles/permissions","type":0,"val":"api","end":""},{"old":"/api/roles/permissions","type":0,"val":"roles","end":""},{"old":"/api/roles/permissions","type":0,"val":"permissions","end":""}],
    types: placeholder as Registry['roles.permissions']['types'],
  },
  'roles.store': {
    methods: ["POST"],
    pattern: '/api/roles',
    tokens: [{"old":"/api/roles","type":0,"val":"api","end":""},{"old":"/api/roles","type":0,"val":"roles","end":""}],
    types: placeholder as Registry['roles.store']['types'],
  },
  'roles.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/roles/:id',
    tokens: [{"old":"/api/roles/:id","type":0,"val":"api","end":""},{"old":"/api/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.show']['types'],
  },
  'roles.update': {
    methods: ["PUT"],
    pattern: '/api/roles/:id',
    tokens: [{"old":"/api/roles/:id","type":0,"val":"api","end":""},{"old":"/api/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.update']['types'],
  },
  'roles.destroy': {
    methods: ["DELETE"],
    pattern: '/api/roles/:id',
    tokens: [{"old":"/api/roles/:id","type":0,"val":"api","end":""},{"old":"/api/roles/:id","type":0,"val":"roles","end":""},{"old":"/api/roles/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['roles.destroy']['types'],
  },
  'roles.users': {
    methods: ["GET","HEAD"],
    pattern: '/api/users',
    tokens: [{"old":"/api/users","type":0,"val":"api","end":""},{"old":"/api/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['roles.users']['types'],
  },
  'roles.assign_role': {
    methods: ["PUT"],
    pattern: '/api/users/:id/role',
    tokens: [{"old":"/api/users/:id/role","type":0,"val":"api","end":""},{"old":"/api/users/:id/role","type":0,"val":"users","end":""},{"old":"/api/users/:id/role","type":1,"val":"id","end":""},{"old":"/api/users/:id/role","type":0,"val":"role","end":""}],
    types: placeholder as Registry['roles.assign_role']['types'],
  },
  'carts.show_wishlist': {
    methods: ["GET","HEAD"],
    pattern: '/api/wishlist',
    tokens: [{"old":"/api/wishlist","type":0,"val":"api","end":""},{"old":"/api/wishlist","type":0,"val":"wishlist","end":""}],
    types: placeholder as Registry['carts.show_wishlist']['types'],
  },
  'carts.add_to_wishlist': {
    methods: ["POST"],
    pattern: '/api/wishlist',
    tokens: [{"old":"/api/wishlist","type":0,"val":"api","end":""},{"old":"/api/wishlist","type":0,"val":"wishlist","end":""}],
    types: placeholder as Registry['carts.add_to_wishlist']['types'],
  },
  'carts.remove_from_wishlist': {
    methods: ["DELETE"],
    pattern: '/api/wishlist/:productId',
    tokens: [{"old":"/api/wishlist/:productId","type":0,"val":"api","end":""},{"old":"/api/wishlist/:productId","type":0,"val":"wishlist","end":""},{"old":"/api/wishlist/:productId","type":1,"val":"productId","end":""}],
    types: placeholder as Registry['carts.remove_from_wishlist']['types'],
  },
  'carts.show_compare': {
    methods: ["GET","HEAD"],
    pattern: '/api/compare',
    tokens: [{"old":"/api/compare","type":0,"val":"api","end":""},{"old":"/api/compare","type":0,"val":"compare","end":""}],
    types: placeholder as Registry['carts.show_compare']['types'],
  },
  'carts.add_to_compare': {
    methods: ["POST"],
    pattern: '/api/compare',
    tokens: [{"old":"/api/compare","type":0,"val":"api","end":""},{"old":"/api/compare","type":0,"val":"compare","end":""}],
    types: placeholder as Registry['carts.add_to_compare']['types'],
  },
  'carts.remove_from_compare': {
    methods: ["DELETE"],
    pattern: '/api/compare/:productId',
    tokens: [{"old":"/api/compare/:productId","type":0,"val":"api","end":""},{"old":"/api/compare/:productId","type":0,"val":"compare","end":""},{"old":"/api/compare/:productId","type":1,"val":"productId","end":""}],
    types: placeholder as Registry['carts.remove_from_compare']['types'],
  },
  'system_config.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/system-config',
    tokens: [{"old":"/api/system-config","type":0,"val":"api","end":""},{"old":"/api/system-config","type":0,"val":"system-config","end":""}],
    types: placeholder as Registry['system_config.index']['types'],
  },
  'system_config.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/system-config/:group',
    tokens: [{"old":"/api/system-config/:group","type":0,"val":"api","end":""},{"old":"/api/system-config/:group","type":0,"val":"system-config","end":""},{"old":"/api/system-config/:group","type":1,"val":"group","end":""}],
    types: placeholder as Registry['system_config.show']['types'],
  },
  'system_config.update': {
    methods: ["PUT"],
    pattern: '/api/system-config/:group',
    tokens: [{"old":"/api/system-config/:group","type":0,"val":"api","end":""},{"old":"/api/system-config/:group","type":0,"val":"system-config","end":""},{"old":"/api/system-config/:group","type":1,"val":"group","end":""}],
    types: placeholder as Registry['system_config.update']['types'],
  },
  'api_keys.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/api-keys',
    tokens: [{"old":"/api/api-keys","type":0,"val":"api","end":""},{"old":"/api/api-keys","type":0,"val":"api-keys","end":""}],
    types: placeholder as Registry['api_keys.index']['types'],
  },
  'api_keys.store': {
    methods: ["POST"],
    pattern: '/api/api-keys',
    tokens: [{"old":"/api/api-keys","type":0,"val":"api","end":""},{"old":"/api/api-keys","type":0,"val":"api-keys","end":""}],
    types: placeholder as Registry['api_keys.store']['types'],
  },
  'api_keys.update': {
    methods: ["PUT"],
    pattern: '/api/api-keys/:id',
    tokens: [{"old":"/api/api-keys/:id","type":0,"val":"api","end":""},{"old":"/api/api-keys/:id","type":0,"val":"api-keys","end":""},{"old":"/api/api-keys/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api_keys.update']['types'],
  },
  'api_keys.destroy': {
    methods: ["DELETE"],
    pattern: '/api/api-keys/:id',
    tokens: [{"old":"/api/api-keys/:id","type":0,"val":"api","end":""},{"old":"/api/api-keys/:id","type":0,"val":"api-keys","end":""},{"old":"/api/api-keys/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['api_keys.destroy']['types'],
  },
  'languages.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/languages',
    tokens: [{"old":"/api/languages","type":0,"val":"api","end":""},{"old":"/api/languages","type":0,"val":"languages","end":""}],
    types: placeholder as Registry['languages.index']['types'],
  },
  'languages.store': {
    methods: ["POST"],
    pattern: '/api/languages',
    tokens: [{"old":"/api/languages","type":0,"val":"api","end":""},{"old":"/api/languages","type":0,"val":"languages","end":""}],
    types: placeholder as Registry['languages.store']['types'],
  },
  'languages.update': {
    methods: ["PUT"],
    pattern: '/api/languages/:id',
    tokens: [{"old":"/api/languages/:id","type":0,"val":"api","end":""},{"old":"/api/languages/:id","type":0,"val":"languages","end":""},{"old":"/api/languages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['languages.update']['types'],
  },
  'languages.destroy': {
    methods: ["DELETE"],
    pattern: '/api/languages/:id',
    tokens: [{"old":"/api/languages/:id","type":0,"val":"api","end":""},{"old":"/api/languages/:id","type":0,"val":"languages","end":""},{"old":"/api/languages/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['languages.destroy']['types'],
  },
  'languages.get_translations': {
    methods: ["GET","HEAD"],
    pattern: '/api/languages/:id/translations',
    tokens: [{"old":"/api/languages/:id/translations","type":0,"val":"api","end":""},{"old":"/api/languages/:id/translations","type":0,"val":"languages","end":""},{"old":"/api/languages/:id/translations","type":1,"val":"id","end":""},{"old":"/api/languages/:id/translations","type":0,"val":"translations","end":""}],
    types: placeholder as Registry['languages.get_translations']['types'],
  },
  'languages.update_translations': {
    methods: ["PUT"],
    pattern: '/api/languages/:id/translations',
    tokens: [{"old":"/api/languages/:id/translations","type":0,"val":"api","end":""},{"old":"/api/languages/:id/translations","type":0,"val":"languages","end":""},{"old":"/api/languages/:id/translations","type":1,"val":"id","end":""},{"old":"/api/languages/:id/translations","type":0,"val":"translations","end":""}],
    types: placeholder as Registry['languages.update_translations']['types'],
  },
  'custom_fields.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/custom-fields',
    tokens: [{"old":"/api/custom-fields","type":0,"val":"api","end":""},{"old":"/api/custom-fields","type":0,"val":"custom-fields","end":""}],
    types: placeholder as Registry['custom_fields.index']['types'],
  },
  'custom_fields.store': {
    methods: ["POST"],
    pattern: '/api/custom-fields',
    tokens: [{"old":"/api/custom-fields","type":0,"val":"api","end":""},{"old":"/api/custom-fields","type":0,"val":"custom-fields","end":""}],
    types: placeholder as Registry['custom_fields.store']['types'],
  },
  'custom_fields.update': {
    methods: ["PUT"],
    pattern: '/api/custom-fields/:id',
    tokens: [{"old":"/api/custom-fields/:id","type":0,"val":"api","end":""},{"old":"/api/custom-fields/:id","type":0,"val":"custom-fields","end":""},{"old":"/api/custom-fields/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['custom_fields.update']['types'],
  },
  'custom_fields.destroy': {
    methods: ["DELETE"],
    pattern: '/api/custom-fields/:id',
    tokens: [{"old":"/api/custom-fields/:id","type":0,"val":"api","end":""},{"old":"/api/custom-fields/:id","type":0,"val":"custom-fields","end":""},{"old":"/api/custom-fields/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['custom_fields.destroy']['types'],
  },
  'custom_fields.get_values': {
    methods: ["GET","HEAD"],
    pattern: '/api/custom-fields/values/:entityType/:entityId',
    tokens: [{"old":"/api/custom-fields/values/:entityType/:entityId","type":0,"val":"api","end":""},{"old":"/api/custom-fields/values/:entityType/:entityId","type":0,"val":"custom-fields","end":""},{"old":"/api/custom-fields/values/:entityType/:entityId","type":0,"val":"values","end":""},{"old":"/api/custom-fields/values/:entityType/:entityId","type":1,"val":"entityType","end":""},{"old":"/api/custom-fields/values/:entityType/:entityId","type":1,"val":"entityId","end":""}],
    types: placeholder as Registry['custom_fields.get_values']['types'],
  },
  'custom_fields.save_values': {
    methods: ["PUT"],
    pattern: '/api/custom-fields/values/:entityType/:entityId',
    tokens: [{"old":"/api/custom-fields/values/:entityType/:entityId","type":0,"val":"api","end":""},{"old":"/api/custom-fields/values/:entityType/:entityId","type":0,"val":"custom-fields","end":""},{"old":"/api/custom-fields/values/:entityType/:entityId","type":0,"val":"values","end":""},{"old":"/api/custom-fields/values/:entityType/:entityId","type":1,"val":"entityType","end":""},{"old":"/api/custom-fields/values/:entityType/:entityId","type":1,"val":"entityId","end":""}],
    types: placeholder as Registry['custom_fields.save_values']['types'],
  },
  'products.adjust_stock': {
    methods: ["POST"],
    pattern: '/api/products/:id/adjust-stock',
    tokens: [{"old":"/api/products/:id/adjust-stock","type":0,"val":"api","end":""},{"old":"/api/products/:id/adjust-stock","type":0,"val":"products","end":""},{"old":"/api/products/:id/adjust-stock","type":1,"val":"id","end":""},{"old":"/api/products/:id/adjust-stock","type":0,"val":"adjust-stock","end":""}],
    types: placeholder as Registry['products.adjust_stock']['types'],
  },
  'exports.leads': {
    methods: ["GET","HEAD"],
    pattern: '/api/export/leads',
    tokens: [{"old":"/api/export/leads","type":0,"val":"api","end":""},{"old":"/api/export/leads","type":0,"val":"export","end":""},{"old":"/api/export/leads","type":0,"val":"leads","end":""}],
    types: placeholder as Registry['exports.leads']['types'],
  },
  'exports.comments': {
    methods: ["GET","HEAD"],
    pattern: '/api/export/comments',
    tokens: [{"old":"/api/export/comments","type":0,"val":"api","end":""},{"old":"/api/export/comments","type":0,"val":"export","end":""},{"old":"/api/export/comments","type":0,"val":"comments","end":""}],
    types: placeholder as Registry['exports.comments']['types'],
  },
  'exports.customers': {
    methods: ["GET","HEAD"],
    pattern: '/api/export/customers',
    tokens: [{"old":"/api/export/customers","type":0,"val":"api","end":""},{"old":"/api/export/customers","type":0,"val":"export","end":""},{"old":"/api/export/customers","type":0,"val":"customers","end":""}],
    types: placeholder as Registry['exports.customers']['types'],
  },
  'exports.report': {
    methods: ["GET","HEAD"],
    pattern: '/api/export/report',
    tokens: [{"old":"/api/export/report","type":0,"val":"api","end":""},{"old":"/api/export/report","type":0,"val":"export","end":""},{"old":"/api/export/report","type":0,"val":"report","end":""}],
    types: placeholder as Registry['exports.report']['types'],
  },
  'replies.generate': {
    methods: ["POST"],
    pattern: '/api/reply/generate',
    tokens: [{"old":"/api/reply/generate","type":0,"val":"api","end":""},{"old":"/api/reply/generate","type":0,"val":"reply","end":""},{"old":"/api/reply/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['replies.generate']['types'],
  },
  'replies.sentiment': {
    methods: ["POST"],
    pattern: '/api/reply/sentiment',
    tokens: [{"old":"/api/reply/sentiment","type":0,"val":"api","end":""},{"old":"/api/reply/sentiment","type":0,"val":"reply","end":""},{"old":"/api/reply/sentiment","type":0,"val":"sentiment","end":""}],
    types: placeholder as Registry['replies.sentiment']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
