/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'auth.register': {
    methods: ["POST"],
    pattern: '/api/auth/register',
    tokens: [{"old":"/api/auth/register","type":0,"val":"api","end":""},{"old":"/api/auth/register","type":0,"val":"auth","end":""},{"old":"/api/auth/register","type":0,"val":"register","end":""}],
    types: placeholder as Registry['auth.register']['types'],
  },
  'auth.login': {
    methods: ["POST"],
    pattern: '/api/auth/login',
    tokens: [{"old":"/api/auth/login","type":0,"val":"api","end":""},{"old":"/api/auth/login","type":0,"val":"auth","end":""},{"old":"/api/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.me': {
    methods: ["GET","HEAD"],
    pattern: '/api/auth/me',
    tokens: [{"old":"/api/auth/me","type":0,"val":"api","end":""},{"old":"/api/auth/me","type":0,"val":"auth","end":""},{"old":"/api/auth/me","type":0,"val":"me","end":""}],
    types: placeholder as Registry['auth.me']['types'],
  },
  'shops.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/shops',
    tokens: [{"old":"/api/shops","type":0,"val":"api","end":""},{"old":"/api/shops","type":0,"val":"shops","end":""}],
    types: placeholder as Registry['shops.index']['types'],
  },
  'shops.store': {
    methods: ["POST"],
    pattern: '/api/shops',
    tokens: [{"old":"/api/shops","type":0,"val":"api","end":""},{"old":"/api/shops","type":0,"val":"shops","end":""}],
    types: placeholder as Registry['shops.store']['types'],
  },
  'shops.find_or_create': {
    methods: ["POST"],
    pattern: '/api/shops/find-or-create',
    tokens: [{"old":"/api/shops/find-or-create","type":0,"val":"api","end":""},{"old":"/api/shops/find-or-create","type":0,"val":"shops","end":""},{"old":"/api/shops/find-or-create","type":0,"val":"find-or-create","end":""}],
    types: placeholder as Registry['shops.find_or_create']['types'],
  },
  'shops.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/shops/:id',
    tokens: [{"old":"/api/shops/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shops.show']['types'],
  },
  'shops.update': {
    methods: ["PUT"],
    pattern: '/api/shops/:id',
    tokens: [{"old":"/api/shops/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shops.update']['types'],
  },
  'shops.destroy': {
    methods: ["DELETE"],
    pattern: '/api/shops/:id',
    tokens: [{"old":"/api/shops/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shops.destroy']['types'],
  },
  'keywords.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/shops/:shopId/keywords',
    tokens: [{"old":"/api/shops/:shopId/keywords","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/keywords","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/keywords","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/keywords","type":0,"val":"keywords","end":""}],
    types: placeholder as Registry['keywords.index']['types'],
  },
  'keywords.store': {
    methods: ["POST"],
    pattern: '/api/shops/:shopId/keywords',
    tokens: [{"old":"/api/shops/:shopId/keywords","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/keywords","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/keywords","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/keywords","type":0,"val":"keywords","end":""}],
    types: placeholder as Registry['keywords.store']['types'],
  },
  'keywords.destroy': {
    methods: ["DELETE"],
    pattern: '/api/shops/:shopId/keywords/:id',
    tokens: [{"old":"/api/shops/:shopId/keywords/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/keywords/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/keywords/:id","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/keywords/:id","type":0,"val":"keywords","end":""},{"old":"/api/shops/:shopId/keywords/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['keywords.destroy']['types'],
  },
  'templates.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/shops/:shopId/templates',
    tokens: [{"old":"/api/shops/:shopId/templates","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/templates","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/templates","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['templates.index']['types'],
  },
  'templates.store': {
    methods: ["POST"],
    pattern: '/api/shops/:shopId/templates',
    tokens: [{"old":"/api/shops/:shopId/templates","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/templates","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/templates","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/templates","type":0,"val":"templates","end":""}],
    types: placeholder as Registry['templates.store']['types'],
  },
  'templates.destroy': {
    methods: ["DELETE"],
    pattern: '/api/shops/:shopId/templates/:id',
    tokens: [{"old":"/api/shops/:shopId/templates/:id","type":0,"val":"api","end":""},{"old":"/api/shops/:shopId/templates/:id","type":0,"val":"shops","end":""},{"old":"/api/shops/:shopId/templates/:id","type":1,"val":"shopId","end":""},{"old":"/api/shops/:shopId/templates/:id","type":0,"val":"templates","end":""},{"old":"/api/shops/:shopId/templates/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['templates.destroy']['types'],
  },
  'products.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/products',
    tokens: [{"old":"/api/products","type":0,"val":"api","end":""},{"old":"/api/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.index']['types'],
  },
  'products.store': {
    methods: ["POST"],
    pattern: '/api/products',
    tokens: [{"old":"/api/products","type":0,"val":"api","end":""},{"old":"/api/products","type":0,"val":"products","end":""}],
    types: placeholder as Registry['products.store']['types'],
  },
  'products.update': {
    methods: ["PUT"],
    pattern: '/api/products/:id',
    tokens: [{"old":"/api/products/:id","type":0,"val":"api","end":""},{"old":"/api/products/:id","type":0,"val":"products","end":""},{"old":"/api/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.update']['types'],
  },
  'products.destroy': {
    methods: ["DELETE"],
    pattern: '/api/products/:id',
    tokens: [{"old":"/api/products/:id","type":0,"val":"api","end":""},{"old":"/api/products/:id","type":0,"val":"products","end":""},{"old":"/api/products/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['products.destroy']['types'],
  },
  'leads.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/leads',
    tokens: [{"old":"/api/leads","type":0,"val":"api","end":""},{"old":"/api/leads","type":0,"val":"leads","end":""}],
    types: placeholder as Registry['leads.index']['types'],
  },
  'leads.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/leads/stats',
    tokens: [{"old":"/api/leads/stats","type":0,"val":"api","end":""},{"old":"/api/leads/stats","type":0,"val":"leads","end":""},{"old":"/api/leads/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['leads.stats']['types'],
  },
  'leads.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/leads/:id',
    tokens: [{"old":"/api/leads/:id","type":0,"val":"api","end":""},{"old":"/api/leads/:id","type":0,"val":"leads","end":""},{"old":"/api/leads/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leads.show']['types'],
  },
  'leads.update': {
    methods: ["PUT"],
    pattern: '/api/leads/:id',
    tokens: [{"old":"/api/leads/:id","type":0,"val":"api","end":""},{"old":"/api/leads/:id","type":0,"val":"leads","end":""},{"old":"/api/leads/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leads.update']['types'],
  },
  'leads.destroy': {
    methods: ["DELETE"],
    pattern: '/api/leads/:id',
    tokens: [{"old":"/api/leads/:id","type":0,"val":"api","end":""},{"old":"/api/leads/:id","type":0,"val":"leads","end":""},{"old":"/api/leads/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leads.destroy']['types'],
  },
  'leads.pipeline_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/leads-pipeline',
    tokens: [{"old":"/api/leads-pipeline","type":0,"val":"api","end":""},{"old":"/api/leads-pipeline","type":0,"val":"leads-pipeline","end":""}],
    types: placeholder as Registry['leads.pipeline_stats']['types'],
  },
  'dashboard.overview': {
    methods: ["GET","HEAD"],
    pattern: '/api/dashboard/overview',
    tokens: [{"old":"/api/dashboard/overview","type":0,"val":"api","end":""},{"old":"/api/dashboard/overview","type":0,"val":"dashboard","end":""},{"old":"/api/dashboard/overview","type":0,"val":"overview","end":""}],
    types: placeholder as Registry['dashboard.overview']['types'],
  },
  'dashboard.recent_leads': {
    methods: ["GET","HEAD"],
    pattern: '/api/dashboard/recent-leads',
    tokens: [{"old":"/api/dashboard/recent-leads","type":0,"val":"api","end":""},{"old":"/api/dashboard/recent-leads","type":0,"val":"dashboard","end":""},{"old":"/api/dashboard/recent-leads","type":0,"val":"recent-leads","end":""}],
    types: placeholder as Registry['dashboard.recent_leads']['types'],
  },
  'dashboard.analytics': {
    methods: ["GET","HEAD"],
    pattern: '/api/dashboard/analytics',
    tokens: [{"old":"/api/dashboard/analytics","type":0,"val":"api","end":""},{"old":"/api/dashboard/analytics","type":0,"val":"dashboard","end":""},{"old":"/api/dashboard/analytics","type":0,"val":"analytics","end":""}],
    types: placeholder as Registry['dashboard.analytics']['types'],
  },
  'dashboard.top_customers': {
    methods: ["GET","HEAD"],
    pattern: '/api/dashboard/top-customers',
    tokens: [{"old":"/api/dashboard/top-customers","type":0,"val":"api","end":""},{"old":"/api/dashboard/top-customers","type":0,"val":"dashboard","end":""},{"old":"/api/dashboard/top-customers","type":0,"val":"top-customers","end":""}],
    types: placeholder as Registry['dashboard.top_customers']['types'],
  },
  'analytics.daily': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/daily',
    tokens: [{"old":"/api/analytics/daily","type":0,"val":"api","end":""},{"old":"/api/analytics/daily","type":0,"val":"analytics","end":""},{"old":"/api/analytics/daily","type":0,"val":"daily","end":""}],
    types: placeholder as Registry['analytics.daily']['types'],
  },
  'analytics.hourly': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/hourly',
    tokens: [{"old":"/api/analytics/hourly","type":0,"val":"api","end":""},{"old":"/api/analytics/hourly","type":0,"val":"analytics","end":""},{"old":"/api/analytics/hourly","type":0,"val":"hourly","end":""}],
    types: placeholder as Registry['analytics.hourly']['types'],
  },
  'analytics.conversion': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/conversion',
    tokens: [{"old":"/api/analytics/conversion","type":0,"val":"api","end":""},{"old":"/api/analytics/conversion","type":0,"val":"analytics","end":""},{"old":"/api/analytics/conversion","type":0,"val":"conversion","end":""}],
    types: placeholder as Registry['analytics.conversion']['types'],
  },
  'analytics.top_keywords': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/top-keywords',
    tokens: [{"old":"/api/analytics/top-keywords","type":0,"val":"api","end":""},{"old":"/api/analytics/top-keywords","type":0,"val":"analytics","end":""},{"old":"/api/analytics/top-keywords","type":0,"val":"top-keywords","end":""}],
    types: placeholder as Registry['analytics.top_keywords']['types'],
  },
  'analytics.summary': {
    methods: ["GET","HEAD"],
    pattern: '/api/analytics/summary',
    tokens: [{"old":"/api/analytics/summary","type":0,"val":"api","end":""},{"old":"/api/analytics/summary","type":0,"val":"analytics","end":""},{"old":"/api/analytics/summary","type":0,"val":"summary","end":""}],
    types: placeholder as Registry['analytics.summary']['types'],
  },
  'notifications.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/notifications',
    tokens: [{"old":"/api/notifications","type":0,"val":"api","end":""},{"old":"/api/notifications","type":0,"val":"notifications","end":""}],
    types: placeholder as Registry['notifications.index']['types'],
  },
  'notifications.unread_count': {
    methods: ["GET","HEAD"],
    pattern: '/api/notifications/unread-count',
    tokens: [{"old":"/api/notifications/unread-count","type":0,"val":"api","end":""},{"old":"/api/notifications/unread-count","type":0,"val":"notifications","end":""},{"old":"/api/notifications/unread-count","type":0,"val":"unread-count","end":""}],
    types: placeholder as Registry['notifications.unread_count']['types'],
  },
  'notifications.mark_read': {
    methods: ["PUT"],
    pattern: '/api/notifications/:id/read',
    tokens: [{"old":"/api/notifications/:id/read","type":0,"val":"api","end":""},{"old":"/api/notifications/:id/read","type":0,"val":"notifications","end":""},{"old":"/api/notifications/:id/read","type":1,"val":"id","end":""},{"old":"/api/notifications/:id/read","type":0,"val":"read","end":""}],
    types: placeholder as Registry['notifications.mark_read']['types'],
  },
  'notifications.mark_all_read': {
    methods: ["PUT"],
    pattern: '/api/notifications/read-all',
    tokens: [{"old":"/api/notifications/read-all","type":0,"val":"api","end":""},{"old":"/api/notifications/read-all","type":0,"val":"notifications","end":""},{"old":"/api/notifications/read-all","type":0,"val":"read-all","end":""}],
    types: placeholder as Registry['notifications.mark_all_read']['types'],
  },
  'customers.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/customers',
    tokens: [{"old":"/api/customers","type":0,"val":"api","end":""},{"old":"/api/customers","type":0,"val":"customers","end":""}],
    types: placeholder as Registry['customers.index']['types'],
  },
  'customers.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/customers/:id',
    tokens: [{"old":"/api/customers/:id","type":0,"val":"api","end":""},{"old":"/api/customers/:id","type":0,"val":"customers","end":""},{"old":"/api/customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['customers.show']['types'],
  },
  'customers.update': {
    methods: ["PUT"],
    pattern: '/api/customers/:id',
    tokens: [{"old":"/api/customers/:id","type":0,"val":"api","end":""},{"old":"/api/customers/:id","type":0,"val":"customers","end":""},{"old":"/api/customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['customers.update']['types'],
  },
  'customers.destroy': {
    methods: ["DELETE"],
    pattern: '/api/customers/:id',
    tokens: [{"old":"/api/customers/:id","type":0,"val":"api","end":""},{"old":"/api/customers/:id","type":0,"val":"customers","end":""},{"old":"/api/customers/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['customers.destroy']['types'],
  },
  'sessions.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/sessions',
    tokens: [{"old":"/api/sessions","type":0,"val":"api","end":""},{"old":"/api/sessions","type":0,"val":"sessions","end":""}],
    types: placeholder as Registry['sessions.index']['types'],
  },
  'sessions.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/sessions/:id',
    tokens: [{"old":"/api/sessions/:id","type":0,"val":"api","end":""},{"old":"/api/sessions/:id","type":0,"val":"sessions","end":""},{"old":"/api/sessions/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['sessions.show']['types'],
  },
  'orders.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders',
    tokens: [{"old":"/api/orders","type":0,"val":"api","end":""},{"old":"/api/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['orders.index']['types'],
  },
  'orders.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders/stats',
    tokens: [{"old":"/api/orders/stats","type":0,"val":"api","end":""},{"old":"/api/orders/stats","type":0,"val":"orders","end":""},{"old":"/api/orders/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['orders.stats']['types'],
  },
  'orders.store': {
    methods: ["POST"],
    pattern: '/api/orders',
    tokens: [{"old":"/api/orders","type":0,"val":"api","end":""},{"old":"/api/orders","type":0,"val":"orders","end":""}],
    types: placeholder as Registry['orders.store']['types'],
  },
  'orders.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/orders/:id',
    tokens: [{"old":"/api/orders/:id","type":0,"val":"api","end":""},{"old":"/api/orders/:id","type":0,"val":"orders","end":""},{"old":"/api/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['orders.show']['types'],
  },
  'orders.update': {
    methods: ["PUT"],
    pattern: '/api/orders/:id',
    tokens: [{"old":"/api/orders/:id","type":0,"val":"api","end":""},{"old":"/api/orders/:id","type":0,"val":"orders","end":""},{"old":"/api/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['orders.update']['types'],
  },
  'orders.destroy': {
    methods: ["DELETE"],
    pattern: '/api/orders/:id',
    tokens: [{"old":"/api/orders/:id","type":0,"val":"api","end":""},{"old":"/api/orders/:id","type":0,"val":"orders","end":""},{"old":"/api/orders/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['orders.destroy']['types'],
  },
  'schedules.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/schedules',
    tokens: [{"old":"/api/schedules","type":0,"val":"api","end":""},{"old":"/api/schedules","type":0,"val":"schedules","end":""}],
    types: placeholder as Registry['schedules.index']['types'],
  },
  'schedules.store': {
    methods: ["POST"],
    pattern: '/api/schedules',
    tokens: [{"old":"/api/schedules","type":0,"val":"api","end":""},{"old":"/api/schedules","type":0,"val":"schedules","end":""}],
    types: placeholder as Registry['schedules.store']['types'],
  },
  'schedules.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/schedules/:id',
    tokens: [{"old":"/api/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['schedules.show']['types'],
  },
  'schedules.update': {
    methods: ["PUT"],
    pattern: '/api/schedules/:id',
    tokens: [{"old":"/api/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['schedules.update']['types'],
  },
  'schedules.destroy': {
    methods: ["DELETE"],
    pattern: '/api/schedules/:id',
    tokens: [{"old":"/api/schedules/:id","type":0,"val":"api","end":""},{"old":"/api/schedules/:id","type":0,"val":"schedules","end":""},{"old":"/api/schedules/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['schedules.destroy']['types'],
  },
  'webhooks.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/webhooks',
    tokens: [{"old":"/api/webhooks","type":0,"val":"api","end":""},{"old":"/api/webhooks","type":0,"val":"webhooks","end":""}],
    types: placeholder as Registry['webhooks.index']['types'],
  },
  'webhooks.store': {
    methods: ["POST"],
    pattern: '/api/webhooks',
    tokens: [{"old":"/api/webhooks","type":0,"val":"api","end":""},{"old":"/api/webhooks","type":0,"val":"webhooks","end":""}],
    types: placeholder as Registry['webhooks.store']['types'],
  },
  'webhooks.update': {
    methods: ["PUT"],
    pattern: '/api/webhooks/:id',
    tokens: [{"old":"/api/webhooks/:id","type":0,"val":"api","end":""},{"old":"/api/webhooks/:id","type":0,"val":"webhooks","end":""},{"old":"/api/webhooks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['webhooks.update']['types'],
  },
  'webhooks.destroy': {
    methods: ["DELETE"],
    pattern: '/api/webhooks/:id',
    tokens: [{"old":"/api/webhooks/:id","type":0,"val":"api","end":""},{"old":"/api/webhooks/:id","type":0,"val":"webhooks","end":""},{"old":"/api/webhooks/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['webhooks.destroy']['types'],
  },
  'activity_logs.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/activity-logs',
    tokens: [{"old":"/api/activity-logs","type":0,"val":"api","end":""},{"old":"/api/activity-logs","type":0,"val":"activity-logs","end":""}],
    types: placeholder as Registry['activity_logs.index']['types'],
  },
  'products.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/inventory/stats',
    tokens: [{"old":"/api/inventory/stats","type":0,"val":"api","end":""},{"old":"/api/inventory/stats","type":0,"val":"inventory","end":""},{"old":"/api/inventory/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['products.stats']['types'],
  },
  'products.adjust_stock': {
    methods: ["POST"],
    pattern: '/api/products/:id/adjust-stock',
    tokens: [{"old":"/api/products/:id/adjust-stock","type":0,"val":"api","end":""},{"old":"/api/products/:id/adjust-stock","type":0,"val":"products","end":""},{"old":"/api/products/:id/adjust-stock","type":1,"val":"id","end":""},{"old":"/api/products/:id/adjust-stock","type":0,"val":"adjust-stock","end":""}],
    types: placeholder as Registry['products.adjust_stock']['types'],
  },
  'products.stock_history': {
    methods: ["GET","HEAD"],
    pattern: '/api/products/:id/stock-history',
    tokens: [{"old":"/api/products/:id/stock-history","type":0,"val":"api","end":""},{"old":"/api/products/:id/stock-history","type":0,"val":"products","end":""},{"old":"/api/products/:id/stock-history","type":1,"val":"id","end":""},{"old":"/api/products/:id/stock-history","type":0,"val":"stock-history","end":""}],
    types: placeholder as Registry['products.stock_history']['types'],
  },
  'products.import_csv': {
    methods: ["POST"],
    pattern: '/api/products/import',
    tokens: [{"old":"/api/products/import","type":0,"val":"api","end":""},{"old":"/api/products/import","type":0,"val":"products","end":""},{"old":"/api/products/import","type":0,"val":"import","end":""}],
    types: placeholder as Registry['products.import_csv']['types'],
  },
  'products.export_csv': {
    methods: ["GET","HEAD"],
    pattern: '/api/products/export',
    tokens: [{"old":"/api/products/export","type":0,"val":"api","end":""},{"old":"/api/products/export","type":0,"val":"products","end":""},{"old":"/api/products/export","type":0,"val":"export","end":""}],
    types: placeholder as Registry['products.export_csv']['types'],
  },
  'products.get_variants': {
    methods: ["GET","HEAD"],
    pattern: '/api/products/:productId/variants',
    tokens: [{"old":"/api/products/:productId/variants","type":0,"val":"api","end":""},{"old":"/api/products/:productId/variants","type":0,"val":"products","end":""},{"old":"/api/products/:productId/variants","type":1,"val":"productId","end":""},{"old":"/api/products/:productId/variants","type":0,"val":"variants","end":""}],
    types: placeholder as Registry['products.get_variants']['types'],
  },
  'products.create_variant': {
    methods: ["POST"],
    pattern: '/api/products/:productId/variants',
    tokens: [{"old":"/api/products/:productId/variants","type":0,"val":"api","end":""},{"old":"/api/products/:productId/variants","type":0,"val":"products","end":""},{"old":"/api/products/:productId/variants","type":1,"val":"productId","end":""},{"old":"/api/products/:productId/variants","type":0,"val":"variants","end":""}],
    types: placeholder as Registry['products.create_variant']['types'],
  },
  'products.update_variant': {
    methods: ["PUT"],
    pattern: '/api/products/:productId/variants/:variantId',
    tokens: [{"old":"/api/products/:productId/variants/:variantId","type":0,"val":"api","end":""},{"old":"/api/products/:productId/variants/:variantId","type":0,"val":"products","end":""},{"old":"/api/products/:productId/variants/:variantId","type":1,"val":"productId","end":""},{"old":"/api/products/:productId/variants/:variantId","type":0,"val":"variants","end":""},{"old":"/api/products/:productId/variants/:variantId","type":1,"val":"variantId","end":""}],
    types: placeholder as Registry['products.update_variant']['types'],
  },
  'products.delete_variant': {
    methods: ["DELETE"],
    pattern: '/api/products/:productId/variants/:variantId',
    tokens: [{"old":"/api/products/:productId/variants/:variantId","type":0,"val":"api","end":""},{"old":"/api/products/:productId/variants/:variantId","type":0,"val":"products","end":""},{"old":"/api/products/:productId/variants/:variantId","type":1,"val":"productId","end":""},{"old":"/api/products/:productId/variants/:variantId","type":0,"val":"variants","end":""},{"old":"/api/products/:productId/variants/:variantId","type":1,"val":"variantId","end":""}],
    types: placeholder as Registry['products.delete_variant']['types'],
  },
  'shipments.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/shipments',
    tokens: [{"old":"/api/shipments","type":0,"val":"api","end":""},{"old":"/api/shipments","type":0,"val":"shipments","end":""}],
    types: placeholder as Registry['shipments.index']['types'],
  },
  'shipments.store': {
    methods: ["POST"],
    pattern: '/api/shipments',
    tokens: [{"old":"/api/shipments","type":0,"val":"api","end":""},{"old":"/api/shipments","type":0,"val":"shipments","end":""}],
    types: placeholder as Registry['shipments.store']['types'],
  },
  'shipments.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/shipments/stats',
    tokens: [{"old":"/api/shipments/stats","type":0,"val":"api","end":""},{"old":"/api/shipments/stats","type":0,"val":"shipments","end":""},{"old":"/api/shipments/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['shipments.stats']['types'],
  },
  'shipments.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/shipments/:id',
    tokens: [{"old":"/api/shipments/:id","type":0,"val":"api","end":""},{"old":"/api/shipments/:id","type":0,"val":"shipments","end":""},{"old":"/api/shipments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shipments.show']['types'],
  },
  'shipments.update_status': {
    methods: ["PUT"],
    pattern: '/api/shipments/:id/status',
    tokens: [{"old":"/api/shipments/:id/status","type":0,"val":"api","end":""},{"old":"/api/shipments/:id/status","type":0,"val":"shipments","end":""},{"old":"/api/shipments/:id/status","type":1,"val":"id","end":""},{"old":"/api/shipments/:id/status","type":0,"val":"status","end":""}],
    types: placeholder as Registry['shipments.update_status']['types'],
  },
  'shipments.tracking': {
    methods: ["GET","HEAD"],
    pattern: '/api/shipments/:id/tracking',
    tokens: [{"old":"/api/shipments/:id/tracking","type":0,"val":"api","end":""},{"old":"/api/shipments/:id/tracking","type":0,"val":"shipments","end":""},{"old":"/api/shipments/:id/tracking","type":1,"val":"id","end":""},{"old":"/api/shipments/:id/tracking","type":0,"val":"tracking","end":""}],
    types: placeholder as Registry['shipments.tracking']['types'],
  },
  'shipments.destroy': {
    methods: ["DELETE"],
    pattern: '/api/shipments/:id',
    tokens: [{"old":"/api/shipments/:id","type":0,"val":"api","end":""},{"old":"/api/shipments/:id","type":0,"val":"shipments","end":""},{"old":"/api/shipments/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['shipments.destroy']['types'],
  },
  'shipments.get_config': {
    methods: ["GET","HEAD"],
    pattern: '/api/shipping/config',
    tokens: [{"old":"/api/shipping/config","type":0,"val":"api","end":""},{"old":"/api/shipping/config","type":0,"val":"shipping","end":""},{"old":"/api/shipping/config","type":0,"val":"config","end":""}],
    types: placeholder as Registry['shipments.get_config']['types'],
  },
  'shipments.save_config': {
    methods: ["PUT"],
    pattern: '/api/shipping/config',
    tokens: [{"old":"/api/shipping/config","type":0,"val":"api","end":""},{"old":"/api/shipping/config","type":0,"val":"shipping","end":""},{"old":"/api/shipping/config","type":0,"val":"config","end":""}],
    types: placeholder as Registry['shipments.save_config']['types'],
  },
  'shipments.test_connection': {
    methods: ["POST"],
    pattern: '/api/shipping/test-connection',
    tokens: [{"old":"/api/shipping/test-connection","type":0,"val":"api","end":""},{"old":"/api/shipping/test-connection","type":0,"val":"shipping","end":""},{"old":"/api/shipping/test-connection","type":0,"val":"test-connection","end":""}],
    types: placeholder as Registry['shipments.test_connection']['types'],
  },
  'shipments.calculate_fee': {
    methods: ["POST"],
    pattern: '/api/shipping/calculate-fee',
    tokens: [{"old":"/api/shipping/calculate-fee","type":0,"val":"api","end":""},{"old":"/api/shipping/calculate-fee","type":0,"val":"shipping","end":""},{"old":"/api/shipping/calculate-fee","type":0,"val":"calculate-fee","end":""}],
    types: placeholder as Registry['shipments.calculate_fee']['types'],
  },
  'shipments.get_carriers': {
    methods: ["GET","HEAD"],
    pattern: '/api/shipping/carriers',
    tokens: [{"old":"/api/shipping/carriers","type":0,"val":"api","end":""},{"old":"/api/shipping/carriers","type":0,"val":"shipping","end":""},{"old":"/api/shipping/carriers","type":0,"val":"carriers","end":""}],
    types: placeholder as Registry['shipments.get_carriers']['types'],
  },
  'exports.leads': {
    methods: ["GET","HEAD"],
    pattern: '/api/export/leads',
    tokens: [{"old":"/api/export/leads","type":0,"val":"api","end":""},{"old":"/api/export/leads","type":0,"val":"export","end":""},{"old":"/api/export/leads","type":0,"val":"leads","end":""}],
    types: placeholder as Registry['exports.leads']['types'],
  },
  'exports.comments': {
    methods: ["GET","HEAD"],
    pattern: '/api/export/comments',
    tokens: [{"old":"/api/export/comments","type":0,"val":"api","end":""},{"old":"/api/export/comments","type":0,"val":"export","end":""},{"old":"/api/export/comments","type":0,"val":"comments","end":""}],
    types: placeholder as Registry['exports.comments']['types'],
  },
  'exports.customers': {
    methods: ["GET","HEAD"],
    pattern: '/api/export/customers',
    tokens: [{"old":"/api/export/customers","type":0,"val":"api","end":""},{"old":"/api/export/customers","type":0,"val":"export","end":""},{"old":"/api/export/customers","type":0,"val":"customers","end":""}],
    types: placeholder as Registry['exports.customers']['types'],
  },
  'exports.report': {
    methods: ["GET","HEAD"],
    pattern: '/api/export/report',
    tokens: [{"old":"/api/export/report","type":0,"val":"api","end":""},{"old":"/api/export/report","type":0,"val":"export","end":""},{"old":"/api/export/report","type":0,"val":"report","end":""}],
    types: placeholder as Registry['exports.report']['types'],
  },
  'replies.generate': {
    methods: ["POST"],
    pattern: '/api/reply/generate',
    tokens: [{"old":"/api/reply/generate","type":0,"val":"api","end":""},{"old":"/api/reply/generate","type":0,"val":"reply","end":""},{"old":"/api/reply/generate","type":0,"val":"generate","end":""}],
    types: placeholder as Registry['replies.generate']['types'],
  },
  'replies.sentiment': {
    methods: ["POST"],
    pattern: '/api/reply/sentiment',
    tokens: [{"old":"/api/reply/sentiment","type":0,"val":"api","end":""},{"old":"/api/reply/sentiment","type":0,"val":"reply","end":""},{"old":"/api/reply/sentiment","type":0,"val":"sentiment","end":""}],
    types: placeholder as Registry['replies.sentiment']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
