/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ActivityLogSchema extends BaseModel {
  static $columns = ['id', 'shopId', 'userId', 'action', 'entityType', 'entityId', 'details', 'ip', 'createdAt'] as const
  $columns = ActivityLogSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopId: number | null
  @column()
  declare userId: number | null
  @column()
  declare action: string
  @column()
  declare entityType: string | null
  @column()
  declare entityId: number | null
  @column()
  declare details: any | null
  @column()
  declare ip: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class ApiKeySchema extends BaseModel {
  static $columns = ['id', 'userId', 'name', 'key', 'secret', 'permissions', 'isActive', 'lastUsedAt', 'expiresAt', 'createdAt', 'updatedAt'] as const
  $columns = ApiKeySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number
  @column()
  declare name: string
  @column()
  declare key: string
  @column()
  declare secret: string | null
  @column()
  declare permissions: any | null
  @column()
  declare isActive: boolean | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class AutoReplyTemplateSchema extends BaseModel {
  static $columns = ['id', 'shopId', 'name', 'template', 'triggerLabel', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = AutoReplyTemplateSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopId: number | null
  @column()
  declare name: string
  @column()
  declare template: string
  @column()
  declare triggerLabel: string | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ChatLogSchema extends BaseModel {
  static $columns = ['id', 'shopId', 'sessionId', 'customerId', 'uniqueId', 'nickname', 'commentText', 'aiLabel', 'aiSummary', 'productIntent', 'platform', 'profileLink', 'createdAt', 'updatedAt'] as const
  $columns = ChatLogSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopId: number | null
  @column()
  declare sessionId: number | null
  @column()
  declare customerId: number | null
  @column()
  declare uniqueId: string | null
  @column()
  declare nickname: string | null
  @column()
  declare commentText: string | null
  @column()
  declare aiLabel: string | null
  @column()
  declare aiSummary: string | null
  @column()
  declare productIntent: string | null
  @column()
  declare platform: string | null
  @column()
  declare profileLink: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomFieldValueSchema extends BaseModel {
  static $columns = ['id', 'customFieldId', 'entityType', 'entityId', 'value'] as const
  $columns = CustomFieldValueSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare customFieldId: number
  @column()
  declare entityType: string
  @column()
  declare entityId: number
  @column()
  declare value: string | null
}

export class CustomFieldSchema extends BaseModel {
  static $columns = ['id', 'shopId', 'name', 'code', 'type', 'options', 'required', 'group', 'sort', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = CustomFieldSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopId: number | null
  @column()
  declare name: string
  @column()
  declare code: string
  @column()
  declare type: string
  @column()
  declare options: any | null
  @column()
  declare required: boolean | null
  @column()
  declare group: string | null
  @column()
  declare sort: number | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomerSchema extends BaseModel {
  static $columns = ['id', 'shopId', 'uniqueId', 'nickname', 'profilePictureUrl', 'profileLink', 'platform', 'totalComments', 'hotCount', 'lastLabel', 'tags', 'notes', 'createdAt', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopId: number | null
  @column()
  declare uniqueId: string
  @column()
  declare nickname: string | null
  @column()
  declare profilePictureUrl: string | null
  @column()
  declare profileLink: string | null
  @column()
  declare platform: string | null
  @column()
  declare totalComments: number | null
  @column()
  declare hotCount: number | null
  @column()
  declare lastLabel: string | null
  @column()
  declare tags: any | null
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LanguageTranslationSchema extends BaseModel {
  static $columns = ['id', 'languageId', 'group', 'key', 'value'] as const
  $columns = LanguageTranslationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare languageId: number
  @column()
  declare group: string
  @column()
  declare key: string
  @column()
  declare value: string | null
}

export class LanguageSchema extends BaseModel {
  static $columns = ['id', 'code', 'name', 'icon', 'isDefault', 'isActive', 'sort', 'createdAt', 'updatedAt'] as const
  $columns = LanguageSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare code: string
  @column()
  declare name: string
  @column()
  declare icon: string | null
  @column()
  declare isDefault: boolean | null
  @column()
  declare isActive: boolean | null
  @column()
  declare sort: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LeadSchema extends BaseModel {
  static $columns = ['id', 'chatLogId', 'customerId', 'uniqueId', 'nickname', 'comment', 'label', 'status', 'notes', 'productIntent', 'createdAt', 'updatedAt'] as const
  $columns = LeadSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare chatLogId: number | null
  @column()
  declare customerId: number | null
  @column()
  declare uniqueId: string | null
  @column()
  declare nickname: string | null
  @column()
  declare comment: string | null
  @column()
  declare label: string | null
  @column()
  declare status: string | null
  @column()
  declare notes: string | null
  @column()
  declare productIntent: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LivestreamSessionSchema extends BaseModel {
  static $columns = ['id', 'shopId', 'platform', 'roomId', 'status', 'viewerCount', 'peakViewers', 'commentCount', 'hotLeadCount', 'startedAt', 'endedAt', 'createdAt', 'updatedAt'] as const
  $columns = LivestreamSessionSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopId: number | null
  @column()
  declare platform: string | null
  @column()
  declare roomId: string | null
  @column()
  declare status: string | null
  @column()
  declare viewerCount: number | null
  @column()
  declare peakViewers: number | null
  @column()
  declare commentCount: number | null
  @column()
  declare hotLeadCount: number | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column.dateTime()
  declare endedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['id', 'userId', 'shopId', 'type', 'title', 'message', 'link', 'isRead', 'createdAt', 'updatedAt'] as const
  $columns = NotificationSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: number | null
  @column()
  declare shopId: string | null
  @column()
  declare type: string
  @column()
  declare title: string
  @column()
  declare message: string | null
  @column()
  declare link: string | null
  @column()
  declare isRead: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class OrderDetailSchema extends BaseModel {
  static $columns = ['id', 'orderId', 'productId', 'name', 'sku', 'qty', 'price', 'tax', 'totalPrice', 'attribute', 'storeId', 'createdAt'] as const
  $columns = OrderDetailSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number
  @column()
  declare productId: number | null
  @column()
  declare name: string
  @column()
  declare sku: string | null
  @column()
  declare qty: number
  @column()
  declare price: string
  @column()
  declare tax: string
  @column()
  declare totalPrice: string
  @column()
  declare attribute: any | null
  @column()
  declare storeId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class OrderHistorySchema extends BaseModel {
  static $columns = ['id', 'orderId', 'orderStatusId', 'content', 'customerId', 'adminId', 'addDate'] as const
  $columns = OrderHistorySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number
  @column()
  declare orderStatusId: number
  @column()
  declare content: string | null
  @column()
  declare customerId: number | null
  @column()
  declare adminId: number | null
  @column.dateTime()
  declare addDate: DateTime | null
}

export class OrderStatusSchema extends BaseModel {
  static $columns = ['id', 'name'] as const
  $columns = OrderStatusSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
}

export class OrderTotalSchema extends BaseModel {
  static $columns = ['id', 'orderId', 'code', 'title', 'value', 'sort', 'createdAt'] as const
  $columns = OrderTotalSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number
  @column()
  declare code: string
  @column()
  declare title: string
  @column()
  declare value: string
  @column()
  declare sort: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class OrderSchema extends BaseModel {
  static $columns = ['id', 'shopId', 'sessionId', 'customerId', 'leadId', 'customerName', 'customerPhone', 'customerAddress', 'status', 'totalAmount', 'items', 'notes', 'trackingNumber', 'paymentMethod', 'paymentStatus', 'confirmedAt', 'shippedAt', 'deliveredAt', 'createdAt', 'updatedAt', 'currency', 'exchangeRate', 'domain'] as const
  $columns = OrderSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopId: number | null
  @column()
  declare sessionId: number | null
  @column()
  declare customerId: number | null
  @column()
  declare leadId: number | null
  @column()
  declare customerName: string | null
  @column()
  declare customerPhone: string | null
  @column()
  declare customerAddress: string | null
  @column()
  declare status: string | null
  @column()
  declare totalAmount: string | null
  @column()
  declare items: any | null
  @column()
  declare notes: string | null
  @column()
  declare trackingNumber: string | null
  @column()
  declare paymentMethod: string | null
  @column()
  declare paymentStatus: string | null
  @column.dateTime()
  declare confirmedAt: DateTime | null
  @column.dateTime()
  declare shippedAt: DateTime | null
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare currency: string | null
  @column()
  declare exchangeRate: string | null
  @column()
  declare domain: string | null
}

export class PasswordResetSchema extends BaseModel {
  static $columns = ['id', 'email', 'storeId', 'token', 'expiresAt', 'createdAt'] as const
  $columns = PasswordResetSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare email: string
  @column()
  declare storeId: number | null
  @column()
  declare token: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class PaymentStatusSchema extends BaseModel {
  static $columns = ['id', 'name'] as const
  $columns = PaymentStatusSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
}

export class ProductBrandSchema extends BaseModel {
  static $columns = ['id', 'shopId', 'name', 'slug', 'logoUrl', 'description', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = ProductBrandSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopId: number | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare logoUrl: string | null
  @column()
  declare description: string | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductCategorySchema extends BaseModel {
  static $columns = ['id', 'shopId', 'name', 'slug', 'description', 'imageUrl', 'parentId', 'sortOrder', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = ProductCategorySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopId: number | null
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare description: string | null
  @column()
  declare imageUrl: string | null
  @column()
  declare parentId: number | null
  @column()
  declare sortOrder: number | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductVariantSchema extends BaseModel {
  static $columns = ['id', 'productId', 'name', 'sku', 'price', 'costPrice', 'stock', 'attributes', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = ProductVariantSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productId: number | null
  @column()
  declare name: string
  @column()
  declare sku: string | null
  @column()
  declare price: string | null
  @column()
  declare costPrice: string | null
  @column()
  declare stock: number | null
  @column()
  declare attributes: any | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ProductSchema extends BaseModel {
  static $columns = ['id', 'shopId', 'name', 'price', 'imageUrl', 'keywords', 'isActive', 'sku', 'stock', 'createdAt', 'updatedAt', 'costPrice', 'category', 'unit', 'barcode', 'categoryId', 'brandId', 'slug', 'description', 'images', 'variants', 'weight', 'isFeatured'] as const
  $columns = ProductSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopId: number | null
  @column()
  declare name: string
  @column()
  declare price: string | null
  @column()
  declare imageUrl: string | null
  @column()
  declare keywords: any | null
  @column()
  declare isActive: boolean | null
  @column()
  declare sku: string | null
  @column()
  declare stock: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare costPrice: string | null
  @column()
  declare category: string | null
  @column()
  declare unit: string | null
  @column()
  declare barcode: string | null
  @column()
  declare categoryId: number | null
  @column()
  declare brandId: number | null
  @column()
  declare slug: string | null
  @column()
  declare description: string | null
  @column()
  declare images: any | null
  @column()
  declare variants: any | null
  @column()
  declare weight: string | null
  @column()
  declare isFeatured: boolean | null
}

export class RoleSchema extends BaseModel {
  static $columns = ['id', 'name', 'displayName', 'description', 'permissions', 'isSystem', 'createdAt', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare displayName: string | null
  @column()
  declare description: string | null
  @column()
  declare permissions: any | null
  @column()
  declare isSystem: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ScheduledLivestreamSchema extends BaseModel {
  static $columns = ['id', 'shopId', 'title', 'description', 'platform', 'productIds', 'script', 'status', 'scheduledAt', 'durationMinutes', 'createdAt', 'updatedAt'] as const
  $columns = ScheduledLivestreamSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopId: number | null
  @column()
  declare title: string
  @column()
  declare description: string | null
  @column()
  declare platform: string | null
  @column()
  declare productIds: any | null
  @column()
  declare script: string | null
  @column()
  declare status: string | null
  @column.dateTime()
  declare scheduledAt: DateTime
  @column()
  declare durationMinutes: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ShipmentHistorySchema extends BaseModel {
  static $columns = ['id', 'shipmentId', 'status', 'location', 'description', 'source', 'createdAt'] as const
  $columns = ShipmentHistorySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shipmentId: number | null
  @column()
  declare status: string
  @column()
  declare location: string | null
  @column()
  declare description: string | null
  @column()
  declare source: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class ShipmentSchema extends BaseModel {
  static $columns = ['id', 'orderId', 'shopId', 'carrier', 'trackingCode', 'status', 'senderName', 'senderPhone', 'senderAddress', 'senderWard', 'senderDistrict', 'senderProvince', 'receiverName', 'receiverPhone', 'receiverAddress', 'receiverWard', 'receiverDistrict', 'receiverProvince', 'shippingFee', 'codAmount', 'insuranceFee', 'weight', 'dimensions', 'carrierOrderCode', 'carrierStatus', 'carrierResponse', 'estimatedDeliveryAt', 'deliveredAt', 'notes', 'createdAt', 'updatedAt'] as const
  $columns = ShipmentSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare orderId: number | null
  @column()
  declare shopId: number | null
  @column()
  declare carrier: string
  @column()
  declare trackingCode: string | null
  @column()
  declare status: string | null
  @column()
  declare senderName: string | null
  @column()
  declare senderPhone: string | null
  @column()
  declare senderAddress: string | null
  @column()
  declare senderWard: string | null
  @column()
  declare senderDistrict: string | null
  @column()
  declare senderProvince: string | null
  @column()
  declare receiverName: string | null
  @column()
  declare receiverPhone: string | null
  @column()
  declare receiverAddress: string | null
  @column()
  declare receiverWard: string | null
  @column()
  declare receiverDistrict: string | null
  @column()
  declare receiverProvince: string | null
  @column()
  declare shippingFee: string | null
  @column()
  declare codAmount: string | null
  @column()
  declare insuranceFee: string | null
  @column()
  declare weight: number | null
  @column()
  declare dimensions: string | null
  @column()
  declare carrierOrderCode: string | null
  @column()
  declare carrierStatus: string | null
  @column()
  declare carrierResponse: string | null
  @column.dateTime()
  declare estimatedDeliveryAt: DateTime | null
  @column.dateTime()
  declare deliveredAt: DateTime | null
  @column()
  declare notes: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ShopKeywordSchema extends BaseModel {
  static $columns = ['id', 'shopId', 'keyword', 'color', 'alertType', 'isActive', 'createdAt', 'updatedAt'] as const
  $columns = ShopKeywordSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopId: number | null
  @column()
  declare keyword: string
  @column()
  declare color: string | null
  @column()
  declare alertType: string | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ShoppingCartSchema extends BaseModel {
  static $columns = ['id', 'identifier', 'instance', 'content', 'storeId', 'createdAt', 'updatedAt'] as const
  $columns = ShoppingCartSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare identifier: string
  @column()
  declare instance: string
  @column()
  declare content: string | null
  @column()
  declare storeId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ShopSchema extends BaseModel {
  static $columns = ['id', 'shopName', 'platform', 'tiktokUsername', 'shopeeId', 'facebookPageId', 'youtubeChannelId', 'isActive', 'createdAt', 'updatedAt', 'moderationBlacklist', 'moderationHideSpam', 'moderationRateLimit', 'moderationMaxPerMinute', 'shippingConfig', 'defaultCarrier', 'senderName', 'senderPhone', 'senderAddress', 'userId'] as const
  $columns = ShopSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopName: string
  @column()
  declare platform: string | null
  @column()
  declare tiktokUsername: string | null
  @column()
  declare shopeeId: string | null
  @column()
  declare facebookPageId: string | null
  @column()
  declare youtubeChannelId: string | null
  @column()
  declare isActive: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare moderationBlacklist: string | null
  @column()
  declare moderationHideSpam: boolean | null
  @column()
  declare moderationRateLimit: boolean | null
  @column()
  declare moderationMaxPerMinute: number | null
  @column()
  declare shippingConfig: any | null
  @column()
  declare defaultCarrier: string | null
  @column()
  declare senderName: string | null
  @column()
  declare senderPhone: string | null
  @column()
  declare senderAddress: string | null
  @column()
  declare userId: number | null
}

export class StockHistorySchema extends BaseModel {
  static $columns = ['id', 'productId', 'shopId', 'userId', 'action', 'quantityChange', 'stockBefore', 'stockAfter', 'reason', 'referenceType', 'referenceId', 'createdAt'] as const
  $columns = StockHistorySchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare productId: number | null
  @column()
  declare shopId: number | null
  @column()
  declare userId: number | null
  @column()
  declare action: string
  @column()
  declare quantityChange: number
  @column()
  declare stockBefore: number
  @column()
  declare stockAfter: number
  @column()
  declare reason: string | null
  @column()
  declare referenceType: string | null
  @column()
  declare referenceId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
}

export class SystemConfigSchema extends BaseModel {
  static $columns = ['id', 'group', 'key', 'value', 'updatedAt'] as const
  $columns = SystemConfigSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare group: string
  @column()
  declare key: string
  @column()
  declare value: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'name', 'fullName', 'email', 'password', 'role', 'avatarUrl', 'isActive', 'lastLoginAt', 'createdAt', 'updatedAt', 'roleId'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string | null
  @column()
  declare avatarUrl: string | null
  @column()
  declare isActive: boolean | null
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare roleId: number | null
}

export class WebhookSchema extends BaseModel {
  static $columns = ['id', 'shopId', 'url', 'events', 'isActive', 'secret', 'lastStatus', 'lastTriggeredAt', 'createdAt', 'updatedAt'] as const
  $columns = WebhookSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare shopId: number | null
  @column()
  declare url: string
  @column()
  declare events: any | null
  @column()
  declare isActive: boolean | null
  @column()
  declare secret: string | null
  @column()
  declare lastStatus: number | null
  @column.dateTime()
  declare lastTriggeredAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
