/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Analytics: () => import('#controllers/analytics_controller'),
  Auth: () => import('#controllers/auth_controller'),
  Customers: () => import('#controllers/customers_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Exports: () => import('#controllers/exports_controller'),
  Keywords: () => import('#controllers/keywords_controller'),
  Leads: () => import('#controllers/leads_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Orders: () => import('#controllers/orders_controller'),
  Products: () => import('#controllers/products_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Replies: () => import('#controllers/replies_controller'),
  Schedules: () => import('#controllers/schedules_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
  Shops: () => import('#controllers/shops_controller'),
  Templates: () => import('#controllers/templates_controller'),
}
